SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{64734B162DA91179}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64744886951A1297}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA6FA1B8}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{64734B16952270E0}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{64744BA0EE8CD54A}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{64734B168E42616F}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA315A22}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{64734B14E0E3FA32}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64744886B60BFDF8}" {
     m_bEnabled 0
    }
   }
  }
 }
}