SCR_GroupRolePresetConfig {
 m_sGroupName "Escouade d'Entraînement"
 m_eGroupRole ASSAULT
 m_sGroupFlagName "infantry"
 m_sGroupDescription "Unité d'entraînement de l'UPO "
 m_iGroupSize 32
 m_iRadioFrequency 38000
 m_sGroupRoleName "Infanterie"
 m_aLoadoutResources {
  "{4422D33726403B54}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Instructeur_Moderne.et"
  "{4422D33726403B54}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Instructeur_Moderne.et"
  "{4422D33726403B54}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Instructeur_Moderne.et"
  "{4422D33726403B54}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Instructeur_Moderne.et"
  "{6FC69726C73FBDFB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Rifleman_Moderne.et"
  "{6FC69726C73FBDFB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Rifleman_Moderne.et"
  "{6FC69726C73FBDFB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Rifleman_Moderne.et"
  "{6FC69726C73FBDFB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Rifleman_Moderne.et"
  "{6FC69726C73FBDFB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Rifleman_Moderne.et"
  "{6FC69726C73FBDFB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Rifleman_Moderne.et"
  "{6FC69726C73FBDFB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Rifleman_Moderne.et"
  "{6FC69726C73FBDFB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Rifleman_Moderne.et"
 }
}