SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 m_aFriendlyFactionsIds {
  "US"
 }
 m_aPredefinedGroups {
  SCR_GroupRolePresetConfig "{6950ED34B9D09B93}" {
   m_eGroupRole ASSAULT
   m_sGroupRoleName "Infanterie"
   m_aLoadoutResources {
    "{80AE18B31FA21033}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Soldier_Moderne.et"
    "{AF849499F67BAD7F}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TeamLeader_Moderne.et"
    "{275D1C3FE4EC157B}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_SquadLeader_Moderne.et"
   }
  }
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EEB3F124F9}" : "{1D2245BA5CB28957}Configs/EntityCatalog/CGQC/InventoryItems_EntityCatalog_CGQC_Moderne.conf" {
  }
 }
}