SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 UIInfo SCR_FactionUIInfo "{68B908121C63B283}" {
  Name "CGQC - Corps de Garde du Québec"
 }
 m_aFriendlyFactionsIds +{
 }
 m_bCreateOnlyPredefinedGroups 1
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EEB3F124F9}" : "{1D2245BA5CB28957}Configs/EntityCatalog/CGQC/InventoryItems_EntityCatalog_CGQC_Moderne.conf" {
  }
 }
}