SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5D4A87E82561D86F}" : "{DB327CCD7CD65D3B}Configs/EntityCatalog/RHS_MSV/MSV_Groups.conf" {
  }
 }
}