SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "CGQC Patches - Circles"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{6A092CEB9AD782A3}" {
   m_sEntityPrefab "{77DC6D0566862A5F}Prefabs/Circle_Patches/CGQC_Patch_Medic.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB9AD7829E}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB9AD7829A}" {
   m_sEntityPrefab "{3FF7AE01A5201EE1}Prefabs/Circle_Patches/CGQC_Patch_NewLogo_embroidery.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB9AD78299}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}