SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "CGQC Patches - Morale"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{6A092CEB960CCAD8}" {
   m_sEntityPrefab "{6DBED5D832D886FB}Prefabs/Morale_Patches/patch_morale_20.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB960CCADB}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB960CCADA}" {
   m_sEntityPrefab "{8B396226C2FEBDD5}Prefabs/Morale_Patches/patch_morale_arna.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB960CCAA5}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB960CCAA4}" {
   m_sEntityPrefab "{E4482D3A3D423F52}Prefabs/Morale_Patches/patch_morale_blackbeard.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB960CF768}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB960CF76A}" {
   m_sEntityPrefab "{AED3426058621261}Prefabs/Morale_Patches/patch_morale_colle.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB960CF765}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB960CF767}" {
   m_sEntityPrefab "{542A1F9045302ECA}Prefabs/Morale_Patches/patch_morale_crevez.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB960CF766}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB960CF761}" {
   m_sEntityPrefab "{C54ECB96832063E3}Prefabs/Morale_Patches/patch_morale_frech.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB960CF760}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB960CF763}" {
   m_sEntityPrefab "{A64F3DD49BD3870E}Prefabs/Morale_Patches/patch_morale_funmeter.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB960CF762}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB960CF770}" {
   m_sEntityPrefab "{D8A71866D3F05A3D}Prefabs/Morale_Patches/patch_morale_mx.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB960CF773}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB960CF772}" {
   m_sEntityPrefab "{9678FCBD1DE9A235}Prefabs/Morale_Patches/patch_morale_roster.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB960CF74D}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}