SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "CGQC Patches - Personal"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{6A092CEB9248A6B3}" {
   m_sEntityPrefab "{E38C11131ADC589E}Prefabs/Personal_Patches/patch_cloutier.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB9248A6B2}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB9248A6B1}" {
   m_sEntityPrefab "{12079B99C5ADEAEF}Prefabs/Personal_Patches/patch_comeau.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB9249551C}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB92495512}" {
   m_sEntityPrefab "{00903DCB29C292D5}Prefabs/Personal_Patches/patch_deslauriers.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB92495513}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB92495510}" {
   m_sEntityPrefab "{3F4776DE3F91C1FA}Prefabs/Personal_Patches/patch_dube.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB92495511}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB92495516}" {
   m_sEntityPrefab "{BCDF61D9270C007E}Prefabs/Personal_Patches/patch_fournier.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB92495517}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB92495514}" {
   m_sEntityPrefab "{939B3992BEF608B4}Prefabs/Personal_Patches/patch_genest.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB92495515}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB9249552A}" {
   m_sEntityPrefab "{33D082EC68C1D4B6}Prefabs/Personal_Patches/patch_lafo.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB9249552B}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB92495528}" {
   m_sEntityPrefab "{1E7F21FA4833896A}Prefabs/Personal_Patches/patch_lauzon.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB92495529}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB9249552F}" {
   m_sEntityPrefab "{2D200EE09E2DBBA0}Prefabs/Personal_Patches/patch_pike.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB9249552C}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB92495532}" {
   m_sEntityPrefab "{02705DF4B69CAC25}Prefabs/Personal_Patches/patch_tremblay.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB92495533}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB9249326C}" {
   m_sEntityPrefab "{7DFB0BB2DF0FDBE6}Prefabs/Personal_Patches/patch_trepanier.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB9249326F}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB9249326E}" {
   m_sEntityPrefab "{BA14D2C232B29082}Prefabs/Personal_Patches/patch_valiquette.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB92493269}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}