SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "CGQC Patches - Roles"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{6A092CEB91DD4B48}" {
   m_sEntityPrefab "{391FF0D3A9613DEA}Prefabs/Role_Patches/role_at.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB91DD4B49}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB91DD4B4A}" {
   m_sEntityPrefab "{D4830F841580F789}Prefabs/Role_Patches/role_dmr.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB91DCEE0F}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB91DCEE0E}" {
   m_sEntityPrefab "{1147564407DB71B6}Prefabs/Role_Patches/role_eod.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB91DCEE09}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB91DCEE08}" {
   m_sEntityPrefab "{D6D502301484882C}Prefabs/Role_Patches/role_inf.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB91DC81D7}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB91DC81D4}" {
   m_sEntityPrefab "{C08A6C5D35CF17A2}Prefabs/Role_Patches/role_jtac.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB91DC81D5}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB91DC81AA}" {
   m_sEntityPrefab "{BB04345B9999BA97}Prefabs/Role_Patches/role_medic.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB91DC67AD}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB91DC67AF}" {
   m_sEntityPrefab "{B3A04708BEA73755}Prefabs/Role_Patches/role_mg.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB91DC351A}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB91DC351B}" {
   m_sEntityPrefab "{1521D194FF8BB035}Prefabs/Role_Patches/role_pl.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB91DC351C}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB91DC351D}" {
   m_sEntityPrefab "{8C3F680DE26C81A5}Prefabs/Role_Patches/role_sl.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB91DC351E}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB91DC351F}" {
   m_sEntityPrefab "{8BF8925C84EA3B66}Prefabs/Role_Patches/role_tl.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB91DC1C38}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A092CEB91DC1C37}" {
   m_sEntityPrefab "{0637830F1C661F2E}Prefabs/Role_Patches/role_xo.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A092CEB91DC1C36}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}