SCR_EntityCatalogMultiList : "{5F7EC52FC40A03E2}Configs/EntityCatalog/US/InventoryItems_EntityCatalog_US.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6A092A46E5D317DB}" : "{ABA4DC944B423BA3}Configs/EntityCatalog/CGQC/CGQC_Patches_Circle.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A092CEBE830C6C3}" : "{AC26197955ECD33A}Configs/EntityCatalog/CGQC/CGQC_Patches_Morale.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A092CEBE98DC36D}" : "{D4708A6259B9FE4D}Configs/EntityCatalog/CGQC/CGQC_Patches_Personal.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A092CEBE6948B7C}" : "{759BCB273FB8CAC3}Configs/EntityCatalog/CGQC/CGQC_Patches_Roles.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A092CEBE7980999}" : "{FA571FB5B6787C21}Configs/EntityCatalog/CGQC/CGQC_Patches_Units.conf" {
  }
 }
}