SCR_PlaceableEntitiesRegistry {
 m_sAddon "cgqc_setup_moderne"
 m_sSourceDirectory "{4CF717A31DA0C850}PrefabsEditable/Auto/Props/Military/Compositions/CGQC"
 m_Prefabs {
  "{D97744B4886417BD}PrefabsEditable/Auto/Props/Military/Compositions/CGQC/E_ArsenalBox_GRIT.et"
 }
}