SCR_PlaceableEntitiesRegistry {
 m_sAddon "cgqc_setup_moderne"
 m_sSourceDirectory "{5BDFDA1C1044A9F6}PrefabsEditable/Auto/Props/Military/Ready_Cage"
 m_Prefabs {
  "{2F34847676F90655}PrefabsEditable/Auto/Props/Military/Ready_Cage/CGQC_Ready_Cage_1.et"
 }
}