SCR_PlaceableEntitiesRegistry {
 m_sAddon "cgqc_setup_moderne"
 m_sSourceDirectory "{1363C8C67EFA3550}PrefabsEditable/Auto/Compositions/Slotted/ARY_Lockers"
 m_Prefabs {
  "{0607FC1461EB56D1}PrefabsEditable/Auto/Compositions/Slotted/ARY_Lockers/E_ARY_Locker_Large_Rack_CGQC_LR.et"
  "{3304B2132BF44CEF}PrefabsEditable/Auto/Compositions/Slotted/ARY_Lockers/E_ARY_Locker_Large_Rack_CGQC_Rocket.et"
  "{12F6F5029640E7B4}PrefabsEditable/Auto/Compositions/Slotted/ARY_Lockers/E_ARY_Locker_Large_WeaponWall_CGQC_Sniper.et"
  "{C2816F35DF4E0624}PrefabsEditable/Auto/Compositions/Slotted/ARY_Lockers/E_ARY_Locker_Large_Rack_CGQC_MG.et"
 }
}