SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5D4A87E86D216247}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5F1D5E6900632334}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{5F1F701B025B7CE7}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{5D4A87E86D2162B7}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{6895004666044A65}" {
     m_sEntityPrefab "{9FDB23F2240C197D}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_1_343.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6895004666044BD7}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{689500461966C41B}" {
     m_sEntityPrefab "{E82129A6CC014809}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_3_152.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{689500461966C5F7}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68AC53AD234FCD1F}" {
     m_sEntityPrefab "{94A3DCC6DD03EEF4}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_4_163.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68AC53AD234FCAFD}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
       m_eRequiredRank LIEUTENANT
      }
     }
    }
   }
  }
 }
}