SCR_MissionHeader {
 World "{4E72A0BF378AE509}Worlds/GameMaster/GameMaster_Kunar.ent"
 m_sName "Zeus - Kunar Province"
 m_sAuthor "KIOK & silent1"
 m_sDescription "Kunar Province is situated in the northeastern region of Afghanistan, known for its rugged mountainous terrain and strategic location along the border with Pakistan. Time to go for a stroll and fuck shit up. "
 m_bIsArmavisionAllowedInMP 1
}