SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{68B9080860BB52A0}" {
   m_sEntityPrefab "{7DB785F294836FF0}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Base.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68B9080860BB529E}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68B9080860BB529C}" {
     m_UiInfo SCR_UIInfo "{68B9083A5F3E76AB}" {
      Name "Rifleman"
      Description "Unité d'infanterie de base"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{68C5090A8F6747F5}" {
   m_sEntityPrefab "{6AEBAAB77D2F7B3F}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TeamLeader.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68C5090A8F674754}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68C5090A8F674757}" {
     m_UiInfo SCR_UIInfo "{68C5090A8F67475A}" {
      Name "TeamLeader"
      Description "Commandant de fireteam"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68B9080860BB5391}" {
   m_sIdentifier "Campaign"
  }
  SCR_EntityCatalogMultiListEntry "{68B9080860BB5CB6}" {
   m_sIdentifier "Variants"
  }
 }
}