SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{68B9080860BB52A0}" {
   m_sEntityPrefab "{FDBB7219367F1ADB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Soldier.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68B9080860BB529E}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68B9080860BB529C}" {
     m_UiInfo SCR_UIInfo "{68B9083A5F3E76AB}" {
      Name "Soldat"
      Description "Unité d'infanterie de base"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68B9080860BB5391}" {
   m_sIdentifier "Campaign"
  }
  SCR_EntityCatalogMultiListEntry "{68B9080860BB5CB6}" {
   m_sIdentifier "Variants"
  }
 }
}