SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{68B9080860BB52A0}" {
   m_sEntityPrefab "{FDBB7219367F1ADB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Soldier.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68B9080860BB529E}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68B9080860BB529C}" {
     m_UiInfo SCR_UIInfo "{68B9083A5F3E76AB}" {
      Name "Soldat"
      Description "Unité d'infanterie de base"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{69C4F51BD311BB9E}" {
   m_sEntityPrefab "{FDF8418A3D7284D7}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_RiflemanLAT.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69C4F51BD311BC2B}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{69C4F51BD311BC28}" {
     m_UiInfo SCR_UIInfo "{69C4F51BD311BC15}" {
      Name "Soldat LAT"
      Description "Unité d'infanterie de base avec lanceur jetable"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{6950ED369107120A}" {
   m_sEntityPrefab "{6AEBAAB77D2F7B3F}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TeamLeader.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6950ED3691071351}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6950ED369107135D}" {
     m_UiInfo SCR_UIInfo "{6950ED369107135C}" {
      Name "Team Leader"
      Description "TL "
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68B9080860BB5391}" {
   m_sIdentifier "Campaign"
  }
  SCR_EntityCatalogMultiListEntry "{68B9080860BB5CB6}" {
   m_sIdentifier "Variants"
  }
 }
}