SCR_EntityCatalogMultiList {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{68C90C5AA986E554}" {
   m_sEntityPrefab "{82D1BF8C4D7CB21B}Prefabs/Groups/INDFOR/Group_CGQC_FireTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68C90C5AA986E55F}" {
    }
    SCR_EntityCatalogSpawnerData "{68C90C5AA986E543}" {
     m_eSlotTypes 7
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68C90C5AA986E50B}" {
   m_sIdentifier "Not Spawned"
  }
 }
}