SCR_EntityCatalogMultiList : "{5F7EC52FC40A03E2}Configs/EntityCatalog/US/InventoryItems_EntityCatalog_US.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA6FA1B8}" {
  }
  SCR_EntityCatalogMultiListEntry "{5CA0A9E60B892D2A}" {
  }
 }
}