OBS_PresentationConfig_List {
 m_aPresentations {
  OBS_PresentationConfig "{6902C7D55D60E887}" {
   m_sPresentationName "CGQC"
   m_aSlides {
    "{C8CF0BEABFA79B79}UI/Textures/screen_logo.edds"
   }
  }
  OBS_PresentationConfig "{691D3E2D90C6CF7B}" {
   m_sPresentationName "Comms"
  }
 }
}