SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{68B9080860BB52A0}" {
   m_sEntityPrefab "{80AE18B31FA21034}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Base_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogSpawnerData "{68B9080860BB529C}" {
     m_UiInfo SCR_UIInfo "{68B9083A5F3E76AB}" {
      Name "Soldat (Garnison)"
     }
    }
   }
  }
  SCR_EntityCatalogEntry "{6950ED369107120A}" {
   m_sEntityPrefab "{4898FCF4BB705D12}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Rifleman_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogSpawnerData "{6950ED369107135D}" {
     m_UiInfo SCR_UIInfo "{6950ED369107135C}" {
      Name "Rifleman"
     }
    }
   }
  }
  SCR_EntityCatalogEntry "{69721A0B2E825FA5}" {
   m_sEntityPrefab "{D2EC8D808A5CD946}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TL_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogSpawnerData "{6950ED369107135D}" {
     m_UiInfo SCR_UIInfo "{6950ED369107135C}" {
     }
    }
   }
  }
  SCR_EntityCatalogEntry "{69721A0B2FBBF166}" {
   m_sEntityPrefab "{6C3086AEE87B91B5}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_SL_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogSpawnerData "{6950ED369107135D}" {
     m_UiInfo SCR_UIInfo "{6950ED369107135C}" {
      Name "Squad Leader"
      Description "SL"
     }
    }
   }
  }
 }
}