SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{68B9080860BB52A0}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68C5090A8F6747F5}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68C63817A655B427}" {
   m_sEntityPrefab "{4898FCF4BB705D12}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Rifleman_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68C63817A655B5A1}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68C63817A655B5A5}" {
     m_UiInfo SCR_UIInfo "{68C63817A655B5A7}" {
      Name "Rifleman"
      Description "Unité d'infanterie de base"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{68CE68606C987A4C}" {
   m_sEntityPrefab "{00ADACA6736212F7}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_LMG_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68CE68606C987BFE}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68CE68606C987BE2}" {
     m_UiInfo SCR_UIInfo "{68CE68606C987BE4}" {
      Name "Light MG"
      Description "MG relativement léger"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{68CE68606F851BF2}" {
   m_sEntityPrefab "{21F14EB1881D4C23}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_MAT_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68CE68606F851B78}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68CE68606F851B7C}" {
     m_UiInfo SCR_UIInfo "{68CE68606F851B61}" {
      Name "Medium Anti-Tank"
      Description "Anti-tankista"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{68CE68606EA6C5B7}" {
   m_sEntityPrefab "{91181717CEA198E4}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Medic_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68CE68606EA6C51A}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68CE68606EA6C51D}" {
     m_UiInfo SCR_UIInfo "{68CE68606EA6C51F}" {
      Name "Medic"
      Description "Ze Lifesaver"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{68C6381458BE0E95}" {
   m_sEntityPrefab "{F619087E723CE627}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Teamleader_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68C6381458BE0E70}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68C6381458BE0E75}" {
     m_UiInfo SCR_UIInfo "{68C6381458BE0E78}" {
      Name "TeamLeader"
      Description "Commandant de fireteam"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{68C83889216AF434}" {
   m_sEntityPrefab "{275D1C3FE4EC157B}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_SquadLeader_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68C83889216AF5B5}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68C83889216AF5B7}" {
     m_UiInfo SCR_UIInfo "{68C83889216AF5BA}" {
      Name "SquadLeader"
      Description "SL "
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{68DA25C871E72B35}" {
   m_sEntityPrefab "{C5215479921A74F2}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Pilot_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68DA25C871E72867}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68DA25C871E7286D}" {
     m_UiInfo SCR_UIInfo "{68DA25C871E72813}" {
      Name "Pilot"
      Description "Heli Pilot"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}