SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{65696ED3D111261A}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69291207EA8454AE}" {
     m_sEntityPrefab "{4F7932733284294A}Prefabs/Pouches/Base/GRS_Radio_JTAC_Pouch_JTAC_L.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69291207EA8454DF}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69291207EB8E7CCF}" {
     m_sEntityPrefab "{D34639188428F3AC}Prefabs/Pouches/Base/GRS_Radio_JTAC_Pouch_JTAC_L_CY.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69291207EB8E7D6C}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69291207E8A2A351}" {
     m_sEntityPrefab "{27D0719EAB4B602F}Prefabs/Pouches/Base/GRS_Radio_JTAC_Pouch_JTAC_L_RG.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69291207E8A2A3F4}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69291207E9A007BC}" {
     m_sEntityPrefab "{2575861CB6080D25}Prefabs/Pouches/RG/GRS_Radio_JTAC_Pouch_RG.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69291207E9A00426}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{692912043241594E}" {
     m_sEntityPrefab "{5121589B48D435DB}Prefabs/Pouches/Base/GRS_Radio_Pouch_343.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69291204324159F5}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69291204483F3CD6}" {
     m_sEntityPrefab "{A153EFD9BF3A5530}Prefabs/Pouches/Black/GRS_Radio_Pouch_343_Black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69291204483F3D74}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{692912044A12FC0C}" {
     m_sEntityPrefab "{D853BB46E67E0333}Prefabs/Pouches/Base/GRS_Radio_Pouch_343_CY.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{692912044A12FC85}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{692912044B17A6AE}" {
     m_sEntityPrefab "{2CC5F3C0C91D90B0}Prefabs/Pouches/Base/GRS_Radio_Pouch_343_RG.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{692912044B17A6C0}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6927259DFA9F5CDF}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{692725835F757CCF}" {
     m_sEntityPrefab "{FD9E405C8D50324E}Prefabs/Backpanels/CGQC_GRS_Radio_Backpack.et"
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{652C421EC0B58AFA}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{695E22141FAEFA6D}" {
     m_sEntityPrefab "{52EF766BC2F64EE0}Prefabs/Items/Equipment/Backpacks/Rucksack/Backpack_IIFS_FieldPack_MARPATWL.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{695E22141FAEFB3E}" {
       m_eItemType BACKPACK
       m_iSupplyCost 3
      }
     }
    }
   }
  }
 }
}