SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{65382371C298FFC1}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{65621322D7FCC1C3}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{65696ED41199D378}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{65696ED4101873D9}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{65696ED410AE1286}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{68B31D61C3C521F0}" {
     m_sEntityPrefab "{86C16544D72A4BFD}Prefabs/Accessories/CGQC_radio_grs_343.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B31D61C3C521A2}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B31D61C00A89ED}" {
     m_sEntityPrefab "{133810B5D3B81E17}Prefabs/Accessories/CGQC_radio_grs_152.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B31D61C00A895A}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B31D61C105959C}" {
     m_sEntityPrefab "{E2C3CAABBD4BE814}Prefabs/Accessories/CGQC_radio_grs_163L.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B31D61C1051376}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B31D61F1F572AB}" {
     m_sEntityPrefab "{9FDB2653D8D8D48B}Prefabs/Accessories/CGQC_radio_grs_163R.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B31D61F1F57213}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}