SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453CE20F8F}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{66E0EBE53D9402B6}" {
     m_sEntityPrefab "{DF94BA05A9AD38E9}Prefabs/Weapons/Rifles/AKS74U/Variants/CGQC_Rifle_AKS74UN_PBS4.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66E0EBE53D9441FD}" {
       m_eItemType SNIPER_RIFLE
       m_eItemMode WEAPON
       m_iSupplyCost 60
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{66E0EBE53D9441E4}" {
         m_vItemOffset 0 0.04 -0.28
         m_vItemRotation -4 0 0
        }
       }
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C630E4538D3163D}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{66E0EBE529F38B98}" {
     m_sEntityPrefab "{AD8B3950DD0FA7E5}Prefabs/Weapons/Magazines/CGQC_Magazine_545x39_RPK_45rnd_Ball.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66E0EBE529F38B42}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}