SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68B9080B80D9BE97}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68C2489F4509B4AB}" {
     m_sEntityPrefab "{FAD7FB97733F08E7}Prefabs/Weapons/Flares/Flare_Mini.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68C2489F4509B5DB}" {
       m_eItemType NON_LETHAL_THROWABLE
       m_iSupplyCost 1
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{68C2489F4509B5DF}" {
         m_vItemOffset -0.072 0.07 0
         m_vItemRotation 0 0 -90
        }
       }
      }
      SCR_EntityCatalogSupportStationResupplyData "{68C2489F4509B5C2}" {
       m_eResupplyType SMOKE
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68C2489F7D1ACE39}" {
     m_sEntityPrefab "{62AC22982827D29A}Prefabs/Weapons/Flares/Flare_RDG2.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68C2489F7D1ACF93}" {
       m_eItemType NON_LETHAL_THROWABLE
       m_iSupplyCost 1
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{68C2489F7D1ACF95}" {
         m_vItemOffset -0.072 0.07 0
         m_vItemRotation 0 0 -90
        }
       }
      }
      SCR_EntityCatalogSupportStationResupplyData "{68C2489F7D1ACF99}" {
       m_eResupplyType SMOKE
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68C2489F7C60E485}" {
     m_sEntityPrefab "{FAD7FB97733F08E7}Prefabs/Weapons/Flares/Flare_Mini.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68C2489F7C60E47E}" {
       m_eItemType NON_LETHAL_THROWABLE
       m_iSupplyCost 1
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{68C2489F7C60E461}" {
         m_vItemOffset -0.072 0.07 0
         m_vItemRotation 0 0 -90
        }
       }
      }
      SCR_EntityCatalogSupportStationResupplyData "{68C2489F7C60E464}" {
       m_eResupplyType SMOKE
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{68B9080B80D9ABA6}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68C2461D1F0268B9}" {
     m_sEntityPrefab "{42232FFE6E7AC415}Prefabs/Items/Core/Wirecutters/wirecutters.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68C2461D1F026839}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{68C2461D07F33542}" {
   m_sIdentifier "CBRN"
   m_aEntities {
    SCR_EntityCatalogEntry "{68C2461D997E6FAD}" {
    }
   }
  }
 }
}