SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453BCB39DC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5C62F7DFB75D81FB}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{6894FD0788EC5C35}" {
     m_sEntityPrefab "{BC1F56A0AEBED7E2}Prefabs/Items/Equipment/Radios/CGQC_Radio_343_fia.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6894FD07B8DA35F2}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68AA5911F6557C24}" {
     m_sEntityPrefab "{6957CA5E33C32DD7}Prefabs/Items/Equipment/Radios/CGQC_Radio_152_fia.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68AA5911F6557D89}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}