SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68B302D51B312B0F}" {
   m_sIdentifier "Radios"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68B302D5119F61C9}" {
     m_sEntityPrefab "{86C16544D72A4BFD}Prefabs/Accessories/CGQC_radio_grs_343.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B302D50FDC11DD}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B302D5D90F2DD4}" {
     m_sEntityPrefab "{133810B5D3B81E17}Prefabs/Accessories/CGQC_radio_grs_152.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B302D5D90F2D72}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B302D5D826C009}" {
     m_sEntityPrefab "{9FDB2653D8D8D48B}Prefabs/Accessories/CGQC_radio_grs_163R.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B302D5D826C1F5}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B302D5DB94396D}" {
     m_sEntityPrefab "{E2C3CAABBD4BE814}Prefabs/Accessories/CGQC_radio_grs_163L.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B302D5DB9406D6}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}