SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68B12D9F17F0D83C}" {
   m_sIdentifier "Medical"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68B12D9F2C69D10C}" {
     m_sEntityPrefab "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B12D9FC9910CE7}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 0
      }
      SCR_EntityCatalogSupportStationResupplyData "{68B12D9FCD3DA046}" {
       m_eResupplyType BANDAGE
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{68B13A80601EE642}" {
   m_sIdentifier "Patches"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68B13A801143B1A3}" {
     m_sEntityPrefab "{3FF7AE01A5201EE1}Prefabs/Circle_Patches/CGQC_Patch_NewLogo_embroidery.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B13A8004A68F68}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B13A899AA5CB7F}" {
     m_sEntityPrefab "{52225CE53BCDFAA0}Prefabs/Circle_Patches/CGQC_Patch_NewLogo_felt.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B13A899AA5C844}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B13A899DDD90F6}" {
     m_sEntityPrefab "{4E548264220D649A}Prefabs/Flag_Patches/Quebec_Flag_Camo.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B13A899DDD90A1}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B13A899CE4519A}" {
     m_sEntityPrefab "{679108DC957C9420}Prefabs/Flag_Patches/Quebec_Flag_Color.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B13A899CE45179}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}