SCR_Faction : "{FC76EA6983CAA3EE}Configs/Factions/CGQC.conf" {
 FactionKey "CGQC_UPO"
 UIInfo SCR_FactionUIInfo "{68B908121C63B283}" {
  Name "CGQC Unité de Préparation Opérationelle"
  Description "Unité de Préparation Opérationelle du CGQC"
  Icon "{571CB87D306C0A64}UI/Textures/Factions/cgqc_faction_newLogo_UPO_128.edds"
 }
 m_aFriendlyFactionsIds {
  "CGQC"
  "US"
 }
 m_aPredefinedGroups {
  SCR_GroupRolePresetConfig "{69510DF3CD917B84}" {
   m_sGroupName "Escouade d'Entraînement"
   m_iGroupSize 32
   m_bCanBeCreatedByPlayer 1
  }
  SCR_GroupRolePresetConfig "{69510DF3C65C7F89}" {
   m_bIsEnabled 0
  }
  SCR_GroupRolePresetConfig "{6951219CB36CC014}" {
   m_bIsEnabled 0
  }
  SCR_GroupRolePresetConfig "{6951219CB1EC35A6}" {
   m_bIsEnabled 0
  }
  SCR_GroupRolePresetConfig "{6951219CCE9986E4}" {
   m_bIsEnabled 0
  }
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EE815FA292}" : "{73B9B2E15E47D550}Configs/EntityCatalog/CGQC/Characters_EntityCatalog_UPO.conf" {
  }
 }
}