SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{69BD12D2FD590566}" {
   m_sEntityPrefab "{395AEFBA305F33D3}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Soldier_Training_Simunition.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69BD12D2FD590551}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{69BD12D2FD59055F}" {
     m_UiInfo SCR_UIInfo "{69BD12D2FD59055E}" {
      Name "Soldat Simunition"
      Description "Soldat Simunition"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{69BD12D201B7E342}" {
   m_sEntityPrefab "{D0CDBC4E94D098A0}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Soldier_Training.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69BD12D201B7E3D8}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{69BD12D201B7E3C6}" {
     m_UiInfo SCR_UIInfo "{69BD12D201B7E3C4}" {
      Name "Soldat"
      Description "Étudiant"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{69BD12D2FD59055C}" {
   m_sEntityPrefab "{3DA369C4E3AA5E28}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Instructor_Training.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69BD12D2FD59055B}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{69BD12D2FD59055A}" {
     m_UiInfo SCR_UIInfo "{69BD12D2FD590559}" {
      Name "Instructeur"
      Description "Instructeur de formation"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}