SCR_EntityCatalogMultiList : "{5F7EC52FC40A03E2}Configs/EntityCatalog/US/InventoryItems_EntityCatalog_US.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{685D55925AB0CBCE}" {
     m_aEntityDataList {
      SCR_ArsenalItem "{685D55925AB0CB5A}" {
       m_eItemType CGQC_TRAINING_ITEM
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69BD2CE4BE9146BC}" {
     m_sEntityPrefab "{48514DE93637DCC2}Prefabs/Weapons/Handguns/M9/Handgun_M9_simunition.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69BD2CE4BE914735}" {
       m_eItemType CGQC_TRAINING_ITEM
       m_eItemMode WEAPON
       m_iSupplyCost 5
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{69BD2CE4BE914732}" {
        }
       }
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69BD2CE4CB658BF6}" {
     m_sEntityPrefab "{A7F4BC9BCE184A66}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine_simunition.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{685D55925AB0CB5A}" {
       m_eItemType CGQC_TRAINING_ITEM
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69BD2CE425A5CD51}" {
     m_sEntityPrefab "{15154DD08F080224}Prefabs/Weapons/MachineGuns/M249/MG_M249_sim.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69BD2CE425A5CDEF}" {
       m_eItemType CGQC_TRAINING_ITEM
       m_eItemMode WEAPON
       m_iSupplyCost 40
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{69BD2CE425A5CDEC}" {
         m_vItemOffset 0 0 -0.15
        }
       }
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA6FA1B8}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{685D55946959D849}" {
     m_aEntityDataList {
      SCR_ArsenalItem "{685D55946959D9CA}" {
       m_eItemType CGQC_TRAINING_ITEM
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69BD2CE4E7855E04}" {
     m_sEntityPrefab "{AE8D39F6AE371C1B}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Sim.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69BD2CE4E7855EA6}" {
       m_eItemType CGQC_TRAINING_ITEM
       m_eItemMode AMMUNITION
       m_iSupplyCost 1
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5CA0A9E60B892D2A}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69BD2CE4A815BC6B}" {
     m_sEntityPrefab "{D56665074AFBE025}Prefabs/Weapons/Grenades/Grenade_M69_Practice.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69BD2CE4A815BCCF}" {
       m_eItemType CGQC_TRAINING_ITEM
       m_iSupplyCost 3
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{69BD2CE4A815BCCC}" {
         m_vItemOffset -0.015 0.015 0
         m_vItemRotation 0 -36 15.8
        }
       }
      }
      SCR_EntityCatalogSupportStationResupplyData "{69BD2CE4A815BCCA}" {
       m_eResupplyType GRENADE
      }
     }
    }
   }
  }
 }
}