SCR_PlaceableEntitiesRegistry {
 m_sAddon "cgqc_training_moderne"
 m_sSourceDirectory "{8723B134D8E1F391}PrefabsEditable/Auto/MP/Spawning"
 m_Prefabs {
  "{0A0287F66C168EF8}PrefabsEditable/Auto/MP/Spawning/E_SpawnPoint_CGQC_UPO.et"
 }
}