ActionManager {
 Contexts {
  ActionContext PACT_TimerContext {
   Flags 0x2 0
   Actions {
    Action PACT_ArmTimer {
     Type Digital
     InputSource InputSourceValue "{69692E33D7552951}" {
      Input "keyboard:KC_F8"
     }
    }
    Action PACT_ResetTimer {
     Type Digital
     InputSource InputSourceValue "{69692E33D4EF1C72}" {
      Input "keyboard:KC_F9"
     }
    }
   }
  }
 }
}