CGQC_RankRosterConfig {
 m_aPlayers {
  CGQC_PlayerEntry "{6970FD39F759EBCA}" {
   m_sIdentityId "f86ee5bc-39bd-4a59-98b7-9caf0ee061b6"
   m_sLabel "Audet"
   m_iRank CGQC_SOLDAT
  }
  CGQC_PlayerEntry "{6970FD389A167990}" {
   m_sIdentityId "daa9fb24-0729-45bb-b41f-324d22ca632b"
   m_sLabel "Forgues"
   m_iRank CGQC_SOLDAT
  }
  CGQC_PlayerEntry "{6970FD388BB99E79}" {
   m_sIdentityId "72c38387-e5fd-46f4-806e-ce1e7c0ce16e"
   m_sLabel "Walker"
   m_iRank CGQC_SOLDAT
  }
 }
}