CGQC_RankRosterConfig {
 m_aPlayers {
  CGQC_PlayerEntry "{6970FD3F10004C98}" {
   m_sIdentityId "fdeca5b5-5cba-403a-8e3a-d598325dbccc"
   m_sLabel "Dubé"
   m_iRank CGQC_SERGENT
   m_sPatch "{3F4776DE3F91C1FA}Prefabs/Personal_Patches/patch_dube.et"
  }
  CGQC_PlayerEntry "{6970FD3F10BE2971}" {
   m_sIdentityId "c6643f04-50cb-461a-b591-b6e6deb63ed9"
   m_sLabel "Fournier"
   m_iRank CGQC_SERGENT
   m_sPatch "{BCDF61D9270C007E}Prefabs/Personal_Patches/patch_fournier.et"
  }
  CGQC_PlayerEntry "{6970FD3F109CA6B3}" {
   m_sIdentityId "cdce42da0-351f-4d03-821b-e89e46b70002"
   m_sLabel "Turcotte"
   m_iRank CGQC_SERGENT
  }
  CGQC_PlayerEntry "{6970FD3ED0A25618}" {
   m_sIdentityId "789954f6-cdb6-4f69-8095-af635b9a78a1"
   m_sLabel "Lauzon"
   m_iRank CGQC_SERGENT
   m_sPatch "{1E7F21FA4833896A}Prefabs/Personal_Patches/patch_lauzon.et"
  }
  CGQC_PlayerEntry "{6970FD3EE2C4EAF0}" {
   m_sIdentityId "dd7969a6-722f-4ae6-a9e7-898ee9e6fea5"
   m_sLabel "Pike"
   m_iRank CGQC_SERGENT
   m_sPatch "{2D200EE09E2DBBA0}Prefabs/Personal_Patches/patch_pike.et"
  }
 }
}