CGQC_RankRosterConfig {
 m_aPlayers {
  CGQC_PlayerEntry "{6970FD3FF94F0D84}" {
   m_sIdentityId "60e84a60-c12f-4b4a-91ed-c294bab6046e"
   m_sLabel "Comeau"
   m_iRank CGQC_ADJUDENT_MAITRE
   m_sHeadPrefab "{3B473755F8A85D65}Prefabs/Characters/Heads/Head_GreekHead_A3_04.et"
   m_sBodyPrefab "{5EE1CAC3D1D1AC46}Prefabs/Characters/Basebody/CharacterBasebody_Asian_03.et"
   m_sPatch "{12079B99C5ADEAEF}Prefabs/Personal_Patches/patch_comeau.et"
  }
 }
}