CGQC_RankRosterConfig {
 m_aPlayers {
  CGQC_PlayerEntry "{6970FD3FEABDB9E1}" {
   m_sIdentityId "e98c24ac-31b8-4647-94f8-c4ffa5bec5fe"
   m_sLabel "Trépanier"
   m_iRank CGQC_SOUS_LIEUTENANT
   m_sPatch "{7DFB0BB2DF0FDBE6}Prefabs/Personal_Patches/patch_trepanier.et"
  }
 }
}