CGQC_RankRosterConfig {
 m_aPlayers {
  CGQC_PlayerEntry "{6970FD3FB965F74C}" {
   m_sIdentityId "120786ec-60cd-4a96-9e10-c846578745f2"
   m_sLabel "Genest"
   m_iRank CGQC_LIEUTENANT
   m_sPatch "{939B3992BEF608B4}Prefabs/Personal_Patches/patch_genest.et"
  }
  CGQC_PlayerEntry "{6970FD3FB9AB8B27}" {
   m_sIdentityId "e1c8cdf2-953a-4db0-be45-2cd8e79556f2"
   m_sLabel "Valiquette"
   m_iRank CGQC_LIEUTENANT
   m_sHeadPrefab "{F5808273F0A0F3AC}Prefabs/Characters/Heads/Head_RussianHead_1.et"
   m_sBodyPrefab "{E5964C6E27D8199E}Prefabs/Characters/Basebody/CharacterBasebody_02.et"
   m_sPatch "{BA14D2C232B29082}Prefabs/Personal_Patches/patch_valiquette.et"
  }
 }
}