CGQC_RankRosterConfig {
 m_aPlayers {
  CGQC_PlayerEntry "{6970FD3F9096BF82}" {
   m_sIdentityId "6538de9f-32ce-41cc-bc6f-844a6a3b2ce8"
   m_sLabel "Laforest"
   m_iRank CGQC_CAPITAINE
   m_sAdminTag "lafo"
   m_sPatch "{33D082EC68C1D4B6}Prefabs/Personal_Patches/patch_lafo.et"
  }
 }
}