CGQC_RankRosterConfig {
 m_aPlayers {
  CGQC_PlayerEntry "{6970FD3F4A5C0FDE}" {
   m_sIdentityId "d7e9113c-f075-41c5-a72a-9ee5187dc723"
   m_sLabel "Cloutier"
   m_iRank CGQC_MAJOR
   m_sAdminTag "clou"
   m_sHeadPrefab "{1B1F4BCCC3A54549}Prefabs/Characters/Heads/Head_Cloutier.et"
   m_sBodyPrefab "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
   m_sPatch "{E38C11131ADC589E}Prefabs/Personal_Patches/patch_cloutier.et"
  }
  CGQC_PlayerEntry "{6970FD3F4A5C0FCD}" {
   m_sIdentityId "c3fcb72f-2f87-4937-8847-1fb62b39a40c"
   m_sLabel "Tremblay"
   m_iRank CGQC_MAJOR
   m_sHeadPrefab "{22EDFA2131C317E9}Prefabs/Characters/Heads/Head_WhiteHead_01.et"
   m_sBodyPrefab "{89C2788E9B1C96B0}Prefabs/Characters/Basebody/CharacterBasebody_01.et"
   m_sPatch "{02705DF4B69CAC25}Prefabs/Personal_Patches/patch_tremblay.et"
  }
 }
}