CGQC_PlayerRosterConfig {
 m_aRankRosters {
  CGQC_RankRosterConfig "{6970FD39FE51C9A8}" : "{5B590093D0692760}Configs/CGQC/01_Sdt.conf" {
  }
  CGQC_RankRosterConfig "{6970FD3892B2107E}" : "{61FBB5C7B2756959}Configs/CGQC/02_Cpl.conf" {
  }
  CGQC_RankRosterConfig "{6970FD389355688F}" : "{4763DE6E3260142C}Configs/CGQC/03_CplC.conf" {
  }
  CGQC_RankRosterConfig "{6970FD3893D3B111}" : "{9850699A69878F75}Configs/CGQC/04_Sgt.conf" {
  }
  CGQC_RankRosterConfig "{6970FD3890228B7F}" : "{E7130F7F6DEA15C4}Configs/CGQC/05_Adju.conf" {
  }
  CGQC_RankRosterConfig "{6970FD383CFF337D}" : "{0431DD513CDBF08B}Configs/CGQC/06_AdjuM.conf" {
  }
  CGQC_RankRosterConfig "{6970FD383D931706}" : "{685BAA3B59A38819}Configs/CGQC/07_AdjuC.conf" {
  }
  CGQC_RankRosterConfig "{6970FD383A590EFB}" : "{5F533B8107C40FEE}Configs/CGQC/08_SLt.conf" {
  }
  CGQC_RankRosterConfig "{6970FD383BC51E1A}" : "{946DF099F6C49FFF}Configs/CGQC/09_Lt.conf" {
  }
  CGQC_RankRosterConfig "{6970FD383B1F551F}" : "{65E677B4E2E5917C}Configs/CGQC/10_Capt.conf" {
  }
  CGQC_RankRosterConfig "{6970FD383365E727}" : "{604D626702053010}Configs/CGQC/11_Maj.conf" {
  }
 }
}