CGQC_PlayerRosterConfig {
 m_aPlayers {
  CGQC_PlayerEntry "{696CE5A19A81445F}" {
   m_sIdentityId "d7e9113c-f075-41c5-a72a-9ee5187dc723"
   m_sLabel "Cloutier"
   m_iRank CGQC_MAJOR
   m_sAdminTag "clou"
   m_sHeadPrefab "{1B1F4BCCC3A54549}Prefabs/Characters/Heads/Head_Cloutier.et"
   m_sBodyPrefab "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
   m_sPatch "{E38C11131ADC589E}Prefabs/Personal_Patches/patch_cloutier.et"
  }
  CGQC_PlayerEntry "{696CE8CDCD9DE438}" {
   m_sIdentityId "c3fcb72f-2f87-4937-8847-1fb62b39a40c"
   m_sLabel "Tremblay"
   m_iRank CGQC_MAJOR
   m_sHeadPrefab "{22EDFA2131C317E9}Prefabs/Characters/Heads/Head_WhiteHead_01.et"
   m_sBodyPrefab "{89C2788E9B1C96B0}Prefabs/Characters/Basebody/CharacterBasebody_01.et"
   m_sPatch "{02705DF4B69CAC25}Prefabs/Personal_Patches/patch_tremblay.et"
  }
  CGQC_PlayerEntry "{696CE8CDE31E6D05}" {
   m_sIdentityId "6538de9f-32ce-41cc-bc6f-844a6a3b2ce8"
   m_sLabel "Laforest"
   m_iRank CAPTAIN
   m_sAdminTag "lafo"
   m_sPatch "{33D082EC68C1D4B6}Prefabs/Personal_Patches/patch_lafo.et"
  }
  CGQC_PlayerEntry "{696CE8CDF3A24230}" {
   m_sIdentityId "120786ec-60cd-4a96-9e10-c846578745f2"
   m_sLabel "Genest"
   m_iRank CGQC_LIEUTENANT
  }
  CGQC_PlayerEntry "{696CE8CD05F67F3D}" {
   m_sIdentityId "e1c8cdf2-953a-4db0-be45-2cd8e79556f2"
   m_sLabel "Valiquette"
   m_iRank CGQC_LIEUTENANT
   m_sHeadPrefab "{F5808273F0A0F3AC}Prefabs/Characters/Heads/Head_RussianHead_1.et"
   m_sBodyPrefab "{E5964C6E27D8199E}Prefabs/Characters/Basebody/CharacterBasebody_02.et"
   m_sPatch "{BA14D2C232B29082}Prefabs/Personal_Patches/patch_valiquette.et"
  }
  CGQC_PlayerEntry "{696CE8CD2B8290CC}" {
   m_sIdentityId "e98c24ac-31b8-4647-94f8-c4ffa5bec5fe"
   m_sLabel "Trépanier"
   m_iRank CGQC_SOUS_LIEUTENANT
   m_sPatch "{7DFB0BB2DF0FDBE6}Prefabs/Personal_Patches/patch_trepanier.et"
  }
  CGQC_PlayerEntry "{696CE8CC94A25166}" {
   m_sIdentityId "60e84a60-c12f-4b4a-91ed-c294bab6046e"
   m_sLabel "Comeau"
   m_iRank CGQC_ADJUDENT_MAITRE
   m_sHeadPrefab "{3B473755F8A85D65}Prefabs/Characters/Heads/Head_GreekHead_A3_04.et"
   m_sBodyPrefab "{5EE1CAC3D1D1AC46}Prefabs/Characters/Basebody/CharacterBasebody_Asian_03.et"
   m_sPatch "{12079B99C5ADEAEF}Prefabs/Personal_Patches/patch_comeau.et"
  }
  CGQC_PlayerEntry "{696CE8CCBAE40D8F}" {
   m_sIdentityId "fdeca5b5-5cba-403a-8e3a-d598325dbccc"
   m_sLabel "Dubé"
   m_iRank CGQC_SERGENT
  }
  CGQC_PlayerEntry "{696CE8CCEC05A831}" {
   m_sIdentityId "c6643f04-50cb-461a-b591-b6e6deb63ed9"
   m_sLabel "Fournier"
   m_iRank CGQC_SERGENT
   m_sPatch "{BCDF61D9270C007E}Prefabs/Personal_Patches/patch_fournier.et"
  }
  CGQC_PlayerEntry "{696CE8CCE06746B0}" {
   m_sIdentityId "cdce42da0-351f-4d03-821b-e89e46b70002"
   m_sLabel "Turcotte"
   m_iRank CGQC_SERGENT
  }
  CGQC_PlayerEntry "{696CE8CCF4C7D4E5}" {
   m_sIdentityId "789954f6-cdb6-4f69-8095-af635b9a78a1"
   m_sLabel "Lauzon"
   m_iRank CGQC_SERGENT
  }
  CGQC_PlayerEntry "{696CE8CC0D4FA8CD}" {
   m_sIdentityId "dd7969a6-722f-4ae6-a9e7-898ee9e6fea5"
   m_sLabel "Pike"
   m_iRank CGQC_SERGENT
   m_sPatch "{2D200EE09E2DBBA0}Prefabs/Personal_Patches/patch_pike.et"
  }
  CGQC_PlayerEntry "{696CE8CC05CFA19A}" {
   m_sIdentityId "72c38387-e5fd-46f4-806e-ce1e7c0ce16e"
   m_sLabel "Walker"
   m_iRank CGQC_SOLDAT
  }
  CGQC_PlayerEntry "{696CE8CC26ED3969}" {
   m_sIdentityId "f86ee5bc-39bd-4a59-98b7-9caf0ee061b6"
   m_sLabel "Audet"
   m_iRank CGQC_SOLDAT
  }
  CGQC_PlayerEntry "{696CE8CC3A91435A}" {
   m_sIdentityId "daa9fb24-0729-45bb-b41f-324d22ca632b"
   m_sLabel "Forgues"
   m_iRank CGQC_SOLDAT
  }
 }
}