CGQC_InspectionConfig {
 m_fWeightYellow 35
 m_fWeightOrange 40
 m_fWeightRed 45
 m_fWeightBlack 50
 m_iPrimaryMagMin 6
 m_aMedicalItems {
  CGQC_InspectionItem "{6986299EEEB92DF7}" {
   m_aPrefabNames {
    "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
   }
   m_sDisplayName "Morphine"
   m_iMinCount 2
  }
  CGQC_InspectionItem "{6986299EFB653012}" {
   m_aPrefabNames {
    "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
    "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
   }
   m_sDisplayName "Bandages"
   m_iMinCount 5
  }
  CGQC_InspectionItem "{6986299E38892503}" {
   m_aPrefabNames {
    "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et"
    "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
   }
   m_sDisplayName "Tourniquet"
   m_iMinCount 2
  }
 }
 m_aCombatItems {
  CGQC_InspectionItem "{69862991B2431B52}" {
   m_aPrefabNames {
    "{E8F00BF730225B00}Prefabs/Weapons/Grenades/Grenade_M67.et"
    "{645C73791ECA1698}Prefabs/Weapons/Grenades/Grenade_RGD5.et"
   }
   m_sDisplayName "Grenade"
   m_iMinCount 2
  }
 }
 m_aAdminItems {
  CGQC_InspectionItem "{6986299E5EB7FC09}" {
   m_aPrefabNames {
    "{7CEF68E2BC68CE71}Prefabs/Items/Equipment/Compass/Compass_Adrianov.et"
    "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
   }
   m_sDisplayName "Boussole"
  }
  CGQC_InspectionItem "{6986299E5C61F743}" {
   m_aPrefabNames {
    "{922F95F91943F69A}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded_US.et"
    "{F849217AB3BA88BE}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded_USSR.et"
    "{983B57B8E95C1F52}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded_FIA.et"
   }
   m_sDisplayName "Map"
  }
 }
}