SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{6972E73788E12B87}" {
   m_Info SCR_UIInfo "{6972E73788E12A66}" {
    Name "UPO"
    Icon "{7B7A5F0D2E0E6D8D}UI/Textures/Factions/cgqc_faction_newLogo_black_128.edds"
   }
   m_LabelType FACTION_UPO
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSettingExtended "{6972E73060948AEE}" {
   m_Info SCR_UIInfo "{6972E730609489FF}" {
    Name "GRIT"
    Icon "{3434B4EF68EE75B2}UI/Textures/cgqc_faction_newLogo_GRIT_128.edds"
   }
   m_LabelType FACTION_GRIT
   m_LabelGroupType FACTION
  }
 }
}