SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68D613E1750C0A4C}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69981ED5C1B77B36}" {
     m_sEntityPrefab "{A21FB863A8066E58}Prefabs/Weapons/Handguns/ARY_1911/ARY_Handgun_1911.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{665B1AF48A156C75}" {
       m_eItemType PISTOL
       m_eItemMode WEAPON
       m_iSupplyCost 5
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{665B1AF48A156C6C}" {
        }
       }
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69981ED5DEAB4682}" {
     m_sEntityPrefab "{2D96BB5F754FD954}Prefabs/Weapons/Handguns/ARY_1911/ARY_Handgun_1911_delta.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{665B3E736DAEE1C4}" {
       m_eItemType PISTOL
       m_eItemMode WEAPON
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{665B3E736DAEE1C5}" {
        }
       }
       m_eRequiredRank LIEUTENANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69981ED5DF510A3A}" {
     m_sEntityPrefab "{3F6CA85A6D4AE898}Prefabs/Weapons/Handguns/ARY_1911/ARY_Handgun_1911_delta_od.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{665D3065C1F2592E}" {
       m_eItemType PISTOL
       m_eItemMode WEAPON
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{665D3065C1F25920}" {
        }
       }
       m_eRequiredRank LIEUTENANT
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{699825949B276702}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69982617CB1BB5D3}" {
     m_sEntityPrefab "{4A1C1BF9AB830BA3}Prefabs/Characters/Berets/CGQC_1_yellow.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B9080B80D8774E}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69982617C600A4BB}" {
     m_sEntityPrefab "{2ED3710551B83182}Prefabs/Characters/Berets/CGQC_2_black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69982617C600A507}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69982617C731E9AE}" {
     m_sEntityPrefab "{FF6A3AE2B9F64309}Prefabs/Characters/Berets/CGQC_3_Green.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69982617C731E9C3}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69982617C7EAFD7A}" {
     m_sEntityPrefab "{B927727621FBF2CB}Prefabs/Characters/Berets/CGQC_4_Gray.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69982617C7EAFD9A}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69982617C4AFC4B4}" {
     m_sEntityPrefab "{F8C081F5D0BAF251}Prefabs/Characters/Berets/CGQC_5_Blue.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69982617C4AFC4D3}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69982617C56B8992}" {
     m_sEntityPrefab "{4C0D703CEF585E02}Prefabs/Characters/Berets/CGQC_6_Red.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69982617C56B8A35}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}