SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{68F8F75DBA7EC6CA}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68F8F75DBA7EC6F9}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68F91A578B32528C}" {
   m_sEntityPrefab "{B980DC6789D231D4}Prefabs/Characters/Factions/INDFOR/CGQC_UPO/Character_CGQC_Student_2026.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68F91A578B325381}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68F91A578B325385}" {
     m_UiInfo SCR_UIInfo "{68F91A578B325388}" {
      Name "Student"
      Description "Élève en formation"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{68F91A55544C380A}" {
   m_sEntityPrefab "{A42CDE97BAFD4444}Prefabs/Characters/Factions/INDFOR/CGQC_UPO/Character_CGQC_Instructor_2026.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68F91A55544C399A}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{68F91A55544C3980}" {
     m_UiInfo SCR_UIInfo "{68F91A55544C3982}" {
      Name "Instructeur"
      Description "Formateur en élévation"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}