SCR_GearPoolConfig {
 m_aGearPool {
  "{D79B01E998A7FEF7}Prefabs/Characters/HeadGear/Hat_BallCap/variants/Hat_ballcap_ATACS_RG.et"
  "{D96B352F9F2603C2}Prefabs/Characters/HeadGear/Hat_BallCap/variants/Hat_ballcap_BLK_ION.et"
  "{C57D07C5FBD2B20A}Prefabs/Characters/HeadGear/Hat_BallCap/variants/Hat_ballcap_BLK_ION2.et"
  "{802EC023B01E5006}Prefabs/Characters/HeadGear/Hat_BallCap/variants/Hat_ballcap_GRY_ION.et"
  "{804440DF8E9B9A40}Prefabs/Characters/HeadGear/Hat_BallCap/variants/Hat_ballcap_OD_ION.et"
  "{C2372185306F6E6C}Prefabs/Characters/HeadGear/Hat_BallCap/variants/Hat_ballcap_OD_Wartech.et"
  "{D495C22614B0327C}Prefabs/Characters/HeadGear/Hat_BallCap/variants/Hat_ballcap_TAN_ION.et"
  "{2146C9C53FCCC74B}Prefabs/Characters/HeadGear/Hat_BallCap/variants/Hat_ballcap_TAN_ION2.et"
  "{C4DA853C33295020}Prefabs/Characters/HeadGear/Hat_BallCap/variants/Hat_ballcap_TAN_ION3.et"
  "{E83E0F1EDE4DBAFD}Prefabs/Characters/HeadGear/Hat_BallCap/variants/Hat_ballcap_TAN_MarsocSniper.et"
  "{F6B252B2ABEA44BA}Prefabs/Characters/HeadGear/Hat_BallCap/variants/Hat_ballcap_TAN_MarsocSniper2.et"
  "{5862DF853F24F2BF}Prefabs/Characters/HeadGear/Hat_Beanie/variants/Hat_beanie_Black_ION.et"
  "{7D12ED385A43B426}Prefabs/Characters/HeadGear/Hat_Beanie/variants/Hat_beanie_Black_ION2.et"
  "{EBC0C74DF9032859}Prefabs/Characters/HeadGear/Hat_Beanie/variants/Hat_beanie_green_ION.et"
  "{44A66B024BB7F36F}Prefabs/Characters/HeadGear/Hat_Beanie/variants/Hat_beanie_green_ION2.et"
  "{52BE66B6E343D441}Prefabs/Characters/HeadGear/Headphones_Impact/Headphones_Impact.et"
  "{EB916F0BF524EF25}Prefabs/Characters/HeadGear/Headphones_Peltor/Headphones_Peltor_black.et"
  "{3FDA3C5B74681C25}Prefabs/Characters/HeadGear/Headphones_Sordin_Liberator/Headphones_liberator.et"
  "{6D6ADA201AD4E09B}Prefabs/Characters/HeadGear/Headphones_Peltor/Headphones_Peltor_olive.et"
  "{85D618A51C013F7A}Prefabs/Characters/HeadGear/Headphones_Peltor/Headphones_Peltor_yellow.et"
  "{63F1353AF0D18504}Prefabs/Characters/HeadGear/Headphones_Sordin_Liberator/Headphones_Sordin_black.et"
 }
}