SCR_PlaceableEntitiesRegistry {
 m_sAddon "cgqc_training"
 m_sSourceDirectory "{1AAA830054D3C0E8}PrefabsEditable/Auto/Props/Military/Arsenal"
 m_Prefabs {
  "{20249A683E463F13}PrefabsEditable/Auto/Props/Military/Arsenal/E_ARY_AmmoBoxArsenal_Weapons_CGQC_Simunition.et"
  "{D2B0F72599E0491B}PrefabsEditable/Auto/Props/Military/Arsenal/E_ARY_Locker_Large_Rack_Large_Simunition.et"
 }
}