FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{646EFE2D234DBAFF}" {
   Headcamo {
    "{E4D015061438274C}Prefabs/Characters/Heads/Head_RussianHead_1_camo.et"
   }
  }
  VisualIdentity "{646EFE2D1CCC6202}" {
   Headcamo {
    "{EACE514E29CF2896}Prefabs/Characters/Heads/Head_RussianHead_2_camo.et"
   }
  }
  VisualIdentity "{5A393A88E392BF36}" {
   Headcamo {
    "{EF3B9289C29DD220}Prefabs/Characters/Heads/Head_RussianHead_3_camo.et"
   }
  }
  VisualIdentity "{646EFE2D144D2D21}" {
   Headcamo {
    "{F6F2D9DE52213722}Prefabs/Characters/Heads/Head_RussianHead_4_camo.et"
   }
  }
  VisualIdentity "{5A393A88E2A84F99}" {
   Headcamo {
    "{F3071A19B973CD94}Prefabs/Characters/Heads/Head_RussianHead_5_camo.et"
   }
  }
  VisualIdentity "{646EFE2FC6DBBC72}" {
   Headcamo {
    "{C73873B02C2A15D5}Prefabs/Characters/Heads/Head_kruglikov_camo.et"
   }
  }
 }
}