SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6972E7303C31FB2B}" {
   m_sEntityPrefab "{02A1D8FDDDFD74D7}Prefabs/Groups/PLASTICBANDIT/Group_PLASTICBANDIT_CQB_20.et"
  }
 }
}