SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68D613E3791B5A3F}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68D613E37DDF920E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{68D61B22A4509B91}" {
     m_sEntityPrefab "{9FDB23F2240C197D}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_1_343.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B2590A358E5405}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68D61B22A6366158}" {
     m_sEntityPrefab "{E82129A6CC014809}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_3_152.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B2590A254BDCE3}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68D61B23591F02AE}" {
     m_sEntityPrefab "{94A3DCC6DD03EEF4}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_4_163.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B2590A246A0239}" {
       m_eItemType EQUIPMENT
       m_eRequiredRank LIEUTENANT
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{68B9080B80D9ABA6}" {
  }
 }
}