SCR_EntityCatalogMultiList : "{5F7EC52FC40A03E2}Configs/EntityCatalog/US/InventoryItems_EntityCatalog_US.conf" {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5C62F7D8F3ED7EFC}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{62511B0E29E392FF}" {
     m_sEntityPrefab "{9FDB23F2240C197D}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_1_343.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{62511B0E2BA1609E}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogEntry "{658923D44D23A30D}" {
     m_sEntityPrefab "{E82129A6CC014809}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_3_152.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{65944C2D611D7940}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogEntry "{658923D44E65E10F}" {
     m_sEntityPrefab "{94A3DCC6DD03EEF4}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_4_163.et"
     m_bEnabled 0
     m_aEntityDataList {
      SCR_ArsenalItem "{65944C2D623A9BB1}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogEntry "{625806F1281C08C6}" {
     m_sEntityPrefab "{25B700594DF082A3}Prefabs/Items/Equipment/Radios/Radio_MR300.et"
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA2B2FF4}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5C62F7D8F231A82E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{628C34ABF3150CC1}" {
     m_sEntityPrefab "{8BAF91E2DA5D7546}Prefabs/Items/Equipment/Radios/Radio_Backpack_LR.et"
    }
   }
  }
 }
}