SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{62492BA9707E9575}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5F1D5E6929D850F8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{5F1F701B141FE129}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{5D7AC44B2A84E3AB}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{65DAF352E68ACE31}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{689500467FA267F2}" {
     m_sEntityPrefab "{9FDB23F2240C197D}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_1_343.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{689500467FA26770}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68950046683EAD34}" {
     m_sEntityPrefab "{E82129A6CC014809}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_3_152.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68950046683EAAE8}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68AC53AD10C3F288}" {
     m_sEntityPrefab "{94A3DCC6DD03EEF4}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_4_163.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68AC53AD10C3F269}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
       m_eRequiredRank LIEUTENANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68AC53AD13D34AF0}" {
     m_sEntityPrefab "{EEEDC5D1AC2CE09F}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_4_163a.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68AC53AD13D34AA6}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
       m_eRequiredRank MAJOR
      }
     }
    }
   }
  }
 }
}