SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6978EB19A107AB82}" {
   m_sIdentifier "CGQC Berets"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6978EB19B7FE9899}" {
     m_sEntityPrefab "{4A1C1BF9AB830BA3}Prefabs/Characters/Berets/CGQC_1_yellow.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C72EDE207B4CF54}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6978EB19C172E5AC}" {
     m_sEntityPrefab "{2ED3710551B83182}Prefabs/Characters/Berets/CGQC_2_black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6978EB19C172E624}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6978EB19DE2B12B5}" {
     m_sEntityPrefab "{FF6A3AE2B9F64309}Prefabs/Characters/Berets/CGQC_3_Green.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6978EB19DE2B12D3}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6978EB19DFAFD5CD}" {
     m_sEntityPrefab "{B927727621FBF2CB}Prefabs/Characters/Berets/CGQC_4_Gray.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6978EB19DFAFD66A}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6978EB19DC96A4FB}" {
     m_sEntityPrefab "{F8C081F5D0BAF251}Prefabs/Characters/Berets/CGQC_5_Blue.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6978EB19DC96A515}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6978EB19DE818186}" {
     m_sEntityPrefab "{4C0D703CEF585E02}Prefabs/Characters/Berets/CGQC_6_Red.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6978EB19DE818227}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}