JWK_ModIntegrationsConfig {
 m_aIntegrations {
  JWK_ModIntegrationConfig "{68F4C92792077A76}" : "{2E197B118580CCA5}Configs/CGQC_CivConfig.conf" {
   m_aFactionAddons {
    JWK_ModFactionAddons "{68EEE457BFAFABFB}" {
     m_aAddVehicles {
      "{7FC3F9F617C308B4}Prefabs/Vehicles/Wheeled/WW2_Bike_Deployable.et"
     }
    }
   }
  }
 }
}