SCR_GearPoolConfig {
 m_aGearPool {
  "{AB9E3D5524876346}Prefabs/Characters/Footwear/Boots_Faradey_1085/Footware_Faradey_1085.et"
  "{660952F979E8EBF2}Prefabs/Characters/Footwear/Boots_solomon_ultra_x/Footwear_Altama_Boots.et"
  "{934C7275AC865817}Prefabs/Characters/Footwear/Boots_BCT/Footwear_BCT.et"
  "{057E63449502EBCA}Prefabs/Characters/Footwear/Boots_Salomon/Footwear_Salomon.et"
  "{92D8AD48BDD4FE1F}Prefabs/Characters/Footwear/GL_Vans.et"
  "{0B487E893D433540}Prefabs/Characters/Footwear/GL_Vans_BW.et"
  "{BEBA05674AF47CA9}Prefabs/Characters/Footwear/GL_Vans_MC.et"
  "{E0611B087A844B9F}Prefabs/Characters/Footwear/Adidas.et"
  "{0C143AB517846219}Prefabs/Characters/Footwear/JungleBoots_01/AF1s.et"
  "{446960BED57E6802}Prefabs/Characters/Footwear/JungleBoots_01/AF1s_Blackout.et"
  "{6039F0A64E05650D}Prefabs/Characters/Footwear/JungleBoots_01/AF1s_White.et"
  "{EA636DA9323B2592}Prefabs/Characters/Footwear/JungleBoots_01/Converse_Black.et"
  "{323DA9BAD472B405}Prefabs/Characters/Footwear/Jordans_Gray.et"
  "{DD34B7BFAF971550}Prefabs/Characters/Footwear/Jordans_Mocha.et"
  "{7CFB6DCCF775B241}Prefabs/Characters/Footwear/JungleBoots_01/Salomon_Blk.et"
  "{91EB0D3D914DCFB4}Prefabs/Characters/Footwear/JungleBoots_01/Salomon_FDEBlack.et"
  "{D1D2AFEB7F7B4970}Prefabs/Characters/Footwear/JungleBoots_01/Vans_Black.et"
  "{62816106E2860D09}Prefabs/Characters/Footwear/JungleBoots_01/Vans_Tan.et"
 }
}