SCR_MapLightConfig {
 m_aMapLightModes {
  SCR_MapLightMode "{52E4D9430AE66027}" {
   m_vColor 0 0 0 1
   m_fOverlayOpacity 0.995
  }
  SCR_MapLightMode "{52E4D94302DF630F}" {
   m_fLightConeOpacity 0.995
  }
  SCR_MapLightMode "{66D0E6951AFEBF51}" {
   m_eMode FLASH_RED
   m_vColor 0.561 0.071 0.071 1
   m_fLightConeOpacity 0.996
  }
 }
}