ACE_SettingsConfig {
 m_aInitialModSettings {
  ACE_Captives_Settings "{66540638C1BB804D}" {
   m_eTakeAICaptiveRequirements FROM_BEHIND_FOR_ARMED
  }
  ACE_CookOff_Settings "{664F3A78A7FAB508}" {
   m_fMaxCookOffDelay 20
  }
  ACE_Finger_Settings "{626D5B540473CB13}" {
   m_fPingRangeM 15
   m_fMapPointingRangeM 15
  }
  ACE_Overheating_Settings "{65FA13A496B871DE}" {
   m_fDefaultAirCoolingScale 1.1
   m_fJamChanceScale 0.9
   m_fMinSmokeTemperature 460
  }
 }
}