SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  SCR_GarbageSystem "{5F10E7EA29B0EDEC}" {
   Rules {
    EntityClassGarbageRule "{60713063DB480AC7}" {
     Lifetime 3600
     PlayerDistance 200
     PlayerLifetimeEffect Pause
    }
    ComponentClassGarbageRule "{6071306334D2708C}" {
     Lifetime 1800
     PlayerDistance 100
     PlayerLifetimeEffect Pause
     LifetimeResetPercentage 50
    }
    EntityClassGarbageRule "{60713063F62751A3}" {
     OnlyDestroyed 1
     Lifetime 120
    }
    ComponentClassGarbageRule "{6582869DE9FA433E}" {
     OnlyDestroyed 1
    }
   }
  }
 }
}