SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{69ED51B42DCCA4D2}" {
   m_sEntityPrefab "{24503F92CD7259EC}Prefabs/Groups/PLASTICBANDIT/Group_PLASTICBANDIT_Squad_CQB.et"
   m_aEntityDataList {
    SCR_EntityCatalogLoadoutData "{69ED51B42DCCDB22}" {
     m_fSpawnSupplyCost 0
    }
    SCR_EntityCatalogEditorData "{69ED51B42DCCDB27}" {
    }
   }
  }
 }
}