FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{612F36AA5AD67CF3}" {
   Headcamo {
    "{AE8DE206909F9627}Prefabs/Characters/Heads/Head_AsianHead_A3_01_camo.et"
   }
  }
  VisualIdentity "{612F36AA58F27D49}" {
   Headcamo {
    "{A093A64EAD6899FD}Prefabs/Characters/Heads/Head_AsianHead_A3_02_camo.et"
   }
  }
  VisualIdentity "{612F36AA589B944E}" {
   Headcamo {
    "{A5666589463A634B}Prefabs/Characters/Heads/Head_AsianHead_A3_03_camo.et"
   }
  }
  VisualIdentity "{61631823241D3BD8}" {
   Headcamo {
    "{BCAF2EDED6868649}Prefabs/Characters/Heads/Head_AsianHead_A3_04_camo.et"
   }
  }
  VisualIdentity "{6163182324B35FF2}" {
   Headcamo {
    "{B95AED193DD47CFF}Prefabs/Characters/Heads/Head_AsianHead_A3_05_camo.et"
   }
  }
  VisualIdentity "{616318231B5F1DC7}" {
   Headcamo {
    "{B744A95100237325}Prefabs/Characters/Heads/Head_AsianHead_A3_06_camo.et"
   }
  }
  VisualIdentity "{616318231B1DE385}" {
   Headcamo {
    "{B2B16A96EB718993}Prefabs/Characters/Heads/Head_AsianHead_A3_07_camo.et"
   }
  }
 }
}