SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{696C327026605021}" {
   m_sEntityPrefab "{FF55A74CE4B891F8}Prefabs/Groups/OPFOR/RHS_AFRF/MSV/VKPO_Demiseason/Group_RHS_RF_MSV_VKPO_DS_CGQC_CQBx5.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{696C32702660504A}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{696C3270266050B5}" {
     m_UiInfo SCR_UIInfo "{696C4D96C8C23606}" {
      Name "CGQC CQB team x5"
     }
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{696C3CF4228750A8}" {
   m_sEntityPrefab "{BA5B0F3A41E5FCC6}Prefabs/Groups/OPFOR/RHS_AFRF/MSV/VKPO_Demiseason/Group_RHS_RF_MSV_VKPO_DS_CGQC_CQBx10.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{696C3CF42287511B}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{696C3CF422875107}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{696C3CF423E59222}" {
   m_sEntityPrefab "{2345B6A35C02CD56}Prefabs/Groups/OPFOR/RHS_AFRF/MSV/VKPO_Demiseason/Group_RHS_RF_MSV_VKPO_DS_CGQC_CQBx20.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{696C3CF423E592B1}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{696C3CF423E592BD}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}