SCR_MissionHeader {
 World "{21435D354FD4F9E5}Worlds/CGQC_Target_Testing.ent"
 m_sName "CGQC RangeTools Testing"
 m_sAuthor "silent1"
 m_sDescription "..."
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "#AR-Scenario_GameMode_DeathMatch"
 m_iPlayerCount 4
}