EditablePrefabsConfig {
 m_Settings {
  EditablePrefabsSetting "{525E861ED7307B31}" {
   m_Components {
    EditablePrefabsComponent_EditableEntity "{52827C18A615D0B4}" {
     m_ImagePlaceholder "{294759224A8F7B2D}UI/Textures/EditorPreviews/System/armareforger-editorPreviewTemplate.edds"
    }
   }
  }
 }
}