SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{696D1132D6C97520}" {
   m_sEntityPrefab "{CA4695C3926A40CF}Prefabs/Characters/Factions/INDFOR/GRIT/Character_GRIT_operator_rattler.et"
  }
  SCR_EntityCatalogEntry "{6972E737B13A5A59}" {
   m_sEntityPrefab "{9E6CD79C95F44322}Prefabs/Characters/Factions/INDFOR/GRIT/Character_GRIT_operator_lvaw.et"
  }
  SCR_EntityCatalogEntry "{6972E737CEEF91DC}" {
   m_sEntityPrefab "{B6C879A3A976E7FD}Prefabs/Characters/Factions/INDFOR/GRIT/Character_GRIT_operator_honeybadger.et"
  }
  SCR_EntityCatalogEntry "{6972E737CFE38B4C}" {
   m_sEntityPrefab "{A92BC6C48A25CC6E}Prefabs/Characters/Factions/INDFOR/GRIT/Character_GRIT_breacher_shotgun.et"
  }
  SCR_EntityCatalogEntry "{6972E737C5A53CA1}" {
   m_sEntityPrefab "{FAD34F20DB459E89}Prefabs/Characters/Factions/INDFOR/GRIT/Character_GRIT_voltigeur_sa58.et"
  }
  SCR_EntityCatalogEntry "{6972E737C2C7046A}" {
   m_sEntityPrefab "{3078DDB147CA3CAB}Prefabs/Characters/Factions/INDFOR/GRIT/Character_GRIT_teamleader.et"
  }
 }
}