FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{646EFE2E2F77B7F1}" {
   Headcamo {
    "{B8F647EBA05E47EC}Prefabs/Characters/Heads/Head_old_man_camo.et"
   }
  }
  VisualIdentity "{5A3AE9823DB6F5B9}" {
   Headcamo {
    "{DBB93A7957C692FE}Prefabs/Characters/Heads/Head_Tanoan_Boss_camo.et"
   }
  }
  VisualIdentity "{646EFE2E27B31355}" {
   Headcamo {
    "{75649A82D90364D9}Prefabs/Characters/Heads/Head_tanoan_01_camo.et"
   }
  }
  VisualIdentity "{646EFE2E032939F3}" {
   Headcamo {
    "{7B7ADECAE4F46B03}Prefabs/Characters/Heads/Head_tanoan_02_camo.et"
   }
  }
  VisualIdentity "{646EFE2E0533E300}" {
   Headcamo {
    "{7E8F1D0D0FA691B5}Prefabs/Characters/Heads/Head_tanoan_03_camo.et"
   }
  }
  VisualIdentity "{646EFE2E7FB89D78}" {
   Headcamo {
    "{6746565A9F1A74B7}Prefabs/Characters/Heads/Head_tanoan_04_camo.et"
   }
  }
  VisualIdentity "{646EFE2E76D91644}" {
   Headcamo {
    "{62B3959D74488E01}Prefabs/Characters/Heads/Head_tanoan_05_camo.et"
   }
  }
  VisualIdentity "{646EFE2E685D83E4}" {
   Headcamo {
    "{6CADD1D549BF81DB}Prefabs/Characters/Heads/Head_tanoan_06_camo.et"
   }
  }
  VisualIdentity "{646EFE2E620AA04D}" {
   Headcamo {
    "{69581212A2ED7B6D}Prefabs/Characters/Heads/Head_tanoan_07_camo.et"
   }
  }
  VisualIdentity "{646EFE2E64ED5496}" {
   Headcamo {
    "{5F3F477A68C64BDF}Prefabs/Characters/Heads/Head_tanoan_08_camo.et"
   }
  }
 }
}