SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 FactionColor 0 0.0467 0.3763 1
 UIInfo SCR_FactionUIInfo "{62394AA4B52816D2}" {
  Name "CGQC"
  Icon "{7108F71EA87FAD37}Configs/Factions/cgqc_faction_newLogo_black_128.edds"
  m_sNameUpper "CGQC"
 }
 m_OutlineFactionColor 0 0.047 0.376 1
 m_NotificationFactionColor 0 0.063 0.533 1
 m_NotificationTextFactionColor 0 0.063 0.533 1
 m_sFactionFlag "{174D8B3191295219}Configs/Factions/cgqc_faction_flag_newLogo.edds"
}