FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{6152787462E15638}" {
   Headcamo {
    "{9A4893348B1AB242}Prefabs/Characters/Heads/Head_Persian_01_camo.et"
   }
  }
  VisualIdentity "{6152787462BDBBA3}" {
   Headcamo {
    "{9456D77CB6EDBD98}Prefabs/Characters/Heads/Head_Persian_02_camo.et"
   }
  }
  VisualIdentity "{615278746177680D}" {
   Headcamo {
    "{91A314BB5DBF472E}Prefabs/Characters/Heads/Head_Persian_03_camo.et"
   }
  }
 }
}