FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{570EDB8787206B1C}" {
   Headcamo {
    "{43AA5BDFE4338F57}Prefabs/Characters/Heads/Head_White_02/Head_White_02_camo_US_01.et"
    "{2FFE6F3F58F70079}Prefabs/Characters/Heads/Head_White_02/Head_White_02_camo_US_02.et"
   }
  }
  VisualIdentity "{570CE64C784286B5}" {
   Headcamo {
    "{51636CA07EC51127}Prefabs/Characters/Heads/Head_White_03/Head_White_03_camo_US_01.et"
    "{FDC271A8FC924801}Prefabs/Characters/Heads/Head_White_03/Head_White_03_camo_US_02.et"
   }
  }
  VisualIdentity "{570CFDC06CAAD480}" {
   Headcamo {
    "{473E20387338226D}Prefabs/Characters/Heads/Head_White_04/Head_White_04_camo_US_01.et"
    "{4697EB99D27CDC4F}Prefabs/Characters/Heads/Head_White_04/Head_White_04_camo_US_02.et"
   }
  }
  VisualIdentity "{570CFDC05A2BFCE8}" {
   Headcamo {
    "{36B119F39289239E}Prefabs/Characters/Heads/Head_White_05/Head_White_05_camo_US_01.et"
    "{94ABF50E76199437}Prefabs/Characters/Heads/Head_White_05/Head_White_05_camo_US_02.et"
   }
  }
  VisualIdentity "{570CFDC037CCBCD3}" {
   Headcamo {
    "{A42053AFB05A218B}Prefabs/Characters/Heads/Head_White_06/Head_White_06_camo_US_01.et"
    "{A01F375D335C7A2C}Prefabs/Characters/Heads/Head_White_06/Head_White_06_camo_US_02.et"
   }
  }
  VisualIdentity "{570CFDC1C8B17A43}" {
   Headcamo {
    "{889ACA9FABA0471F}Prefabs/Characters/Heads/Head_White_08/Head_White_08_camo_US_01.et"
    "{9444E2D4C76B6423}Prefabs/Characters/Heads/Head_White_08/Head_White_08_camo_US_02.et"
   }
  }
  VisualIdentity "{588508C196393A8F}" {
   Headcamo {
    "{F915F3544A1146EC}Prefabs/Characters/Heads/Head_White_09/Head_White_09_camo_US_01.et"
    "{4678FC43630E2C5B}Prefabs/Characters/Heads/Head_White_09/Head_White_09_camo_US_02.et"
   }
  }
  VisualIdentity "{588508C1951A8A0F}" {
   Headcamo {
    "{7E7987E31FB379BF}Prefabs/Characters/Heads/Head_White_10/Head_White_10_camo_US_01.et"
    "{3A4B78A288F46331}Prefabs/Characters/Heads/Head_White_10/Head_White_10_camo_US_02.et"
   }
  }
  VisualIdentity "{612F36B5AB5708BE}" {
   Headcamo {
    "{6794AC12C8A7A920}Prefabs/Characters/Heads/Head_GreekHead_A3_01_camo.et"
   }
  }
  VisualIdentity "{612F36B5AA7CEEC9}" {
   Headcamo {
    "{698AE85AF550A6FA}Prefabs/Characters/Heads/Head_GreekHead_A3_02_camo.et"
   }
  }
  VisualIdentity "{612F36B5AA0D1BB9}" {
   Headcamo {
    "{6C7F2B9D1E025C4C}Prefabs/Characters/Heads/Head_GreekHead_A3_03_camo.et"
   }
  }
  VisualIdentity "{612F36B5AAF56F1B}" {
   Headcamo {
    "{75B660CA8EBEB94E}Prefabs/Characters/Heads/Head_GreekHead_A3_04_camo.et"
   }
  }
  VisualIdentity "{6173055C777CF9AF}" {
   Headcamo {
    "{9994EC573DF5C56C}Prefabs/Characters/Heads/Head_GreekHead_A3_11_camo.et"
   }
  }
  VisualIdentity "{6173055C6C8A944C}" {
   Headcamo {
    "{978AA81F0002CAB6}Prefabs/Characters/Heads/Head_GreekHead_A3_12_camo.et"
   }
  }
  VisualIdentity "{6173055C628EFBB8}" {
   Headcamo {
    "{927F6BD8EB503000}Prefabs/Characters/Heads/Head_GreekHead_A3_13_camo.et"
   }
  }
  VisualIdentity "{6173055C6704573D}" {
   Headcamo {
    "{8BB6208F7BECD502}Prefabs/Characters/Heads/Head_GreekHead_A3_14_camo.et"
   }
  }
  VisualIdentity "{615E7CB8B523C2E9}" {
   Headcamo {
    "{F9BE8963D8541359}Prefabs/Characters/Heads/Head_IG_leader_camo.et"
   }
  }
  VisualIdentity "{646EFE2C7FF196AA}" {
   Headcamo {
    "{C46FFB6FC907297C}Prefabs/Characters/Heads/Head_Ioannou_camo.et"
   }
  }
  VisualIdentity "{646EFE2EDAD7A533}" {
   Headcamo {
    "{0F0C5339381A3033}Prefabs/Characters/Heads/Head_Mavros_camo.et"
   }
  }
  VisualIdentity "{61431130F1F27FB7}" {
   Headcamo {
    "{A62FB2F4A09D9165}Prefabs/Characters/Heads/Head_Nikos_camo.et"
   }
  }
 }
}