SCR_MissionHeader {
 World "{DD07FA7AD3C47DFA}cgqc_kunar.ent"
 m_sName "Kunar Province"
 m_sAuthor "KIOK & silent1"
 m_sDescription "La province de Kunar est située dans le nord-est de l'Afghanistan et se caractérise par des montagnes accidentées, des vallées étroites et un réseau routier limité qui façonnent les opérations militaires."
 m_sDetails "La province de Kunar présente un terrain montagneux escarpé, des vallées étroites et une infrastructure routière limitée. Les opérations d'infanterie dominent la région, tandis que les déplacements de véhicules sont restreints aux routes principales et aux fonds de vallée. Le contrôle des points hauts, les tactiques d'embuscade et les missions de patrouille sont au cœur du gameplay. L'environnement se prête particulièrement bien à la guerre asymétrique, à la reconnaissance et aux opérations de petites unités."
 m_bIsArmavisionAllowedInMP 1
}