SCR_MissionHeader {
 World "{BECF4E8837AF5608}CGQC_Fort_Stewart.ent"
 m_sName "Fort Stewart 1985 - CGQC"
 m_sAuthor "Mytharium & silent1"
 m_sDescription "Fort Stewart, Géorgie. Installation de l'armée américaine et base permanente de la 3e Division d'infanterie. Le CGQC y opère en qualité d'unité invitée, intégré aux infrastructures d'entraînement de la Rock of the Marne. Qualification sur toutes les armes organiques de l'unité et navigation terrestre en environnement boisé et marécageux caractéristique du sud-est géorgien. Procédures et standards OTAN en vigueur."
 m_sIcon "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sLoadingScreen "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sPreviewImage "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
 m_fXpMultiplier 0
 m_bIsArmavisionAllowedInMP 1
 m_eGME_GlobalAISkill REGULAR
 m_fWeaponFiredReactionDistance 300
}