SCR_MissionHeader {
 World "{74F70C1DD3C7EA67}Fort_Stewar_UPO.ent"
 m_sName "Fort Stewart - CGQC"
 m_sAuthor "Mytharium & silent1"
 m_sPath "{D551D90BDFDB4B93}Missions/Fort_Stewart_UPO.conf"
 m_sDescription "Une version du Fort Stewart adaptée au besoins du groupe CGQC"
 m_sLoadingScreen "{5FB5A1F5B2F76E73}Images/Preview Images/FortStewart_JPG.edds"
 m_sPreviewImage "{5FB5A1F5B2F76E73}Images/Preview Images/FortStewart_JPG.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
 m_fXpMultiplier 0
 m_bIsArmavisionAllowedInMP 1
}