SCR_MissionHeaderCampaign {
 World "{87646DE8A11A8780}Worlds/cgqc_training_vanilla.ent"
 m_sName "CGQC Training Facility"
 m_sAuthor "silent1"
 m_sDescription "Map de training pour le groupe CGQC"
 m_sIcon "{1243B6B8A9CADFF4}UI/Textures/Mission Icons/mission_icon_training.edds"
 m_sLoadingScreen "{846D91EC29C04CA3}UI/Textures/MissionLoadingScreens/mission_preview.edds"
 m_sPreviewImage "{846D91EC29C04CA3}UI/Textures/MissionLoadingScreens/mission_preview.edds"
 m_sGameMode "Training"
 m_iPlayerCount 64
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_eStartingRank MAJOR
}