SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{696D113F4BBDFE4B}" {
   m_sCallsign "#AR-Callsign_US_Company_A"
  }
  SCR_CallsignInfo "{696D113F4BBDFE5F}" {
   m_sCallsign "#AR-Callsign_US_Company_B"
  }
  SCR_CallsignInfo "{696D113F4BBDFE5E}" {
   m_sCallsign "#AR-Callsign_US_Company_C"
  }
  SCR_CallsignInfo "{696D113F4BBDFE59}" {
   m_sCallsign "#AR-Callsign_US_Company_D"
  }
  SCR_CallsignInfo "{696D113F4BBDFE58}" {
   m_sCallsign "#AR-Callsign_US_Company_E"
  }
  SCR_CallsignInfo "{696D113F4BBD4741}" {
   m_sCallsign "#AR-Callsign_US_Company_F"
  }
  SCR_CallsignInfo "{696D113F4BBD4742}" {
   m_sCallsign "#AR-Callsign_US_Company_G"
  }
  SCR_CallsignInfo "{696D113F4BBD4743}" {
   m_sCallsign "#AR-Callsign_US_Company_H"
  }
 }
 m_aPlatoonNames {
  SCR_CallsignInfo "{696D113F4BBD474C}" {
   m_sCallsign "#AR-Callsign_US_Platoon_1"
  }
  SCR_CallsignInfo "{696D113F4BBD474E}" {
   m_sCallsign "#AR-Callsign_US_Platoon_2"
  }
  SCR_CallsignInfo "{696D113F4BBD75AB}" {
   m_sCallsign "#AR-Callsign_US_Platoon_3"
  }
  SCR_CallsignInfo "{696D113F4BBD75AD}" {
   m_sCallsign "#AR-Callsign_US_Platoon_4"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{696D113F4BBD75AC}" {
   m_sCallsign "Rafale"
  }
  SCR_CallsignInfo "{696D113F4BBD759F}" {
   m_sCallsign "Orage"
  }
  SCR_CallsignInfo "{696D113F4BBD759E}" {
   m_sCallsign "Tempête"
  }
  SCR_CallsignInfo "{696D113E9C4C20AC}" {
   m_sCallsign "Verglas"
  }
  SCR_CallsignInfo "{696D113E9986C323}" {
   m_sCallsign "Blizzard"
  }
  SCR_CallsignInfo "{696D113F4BBD759C}" {
   m_sCallsign "Éclair"
  }
 }
 m_sCallsignGroupFormat "%3"
 m_sCallsignCharacterFormat "%4"
 m_sCallsignCharacterWithRoleFormat "%1 %2 %3: %4"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{696D113F4BBD7581}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{696D113F4BBD7583}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{696D113F4BBD7582}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}