SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{6910F9F1D17367BE}" {
   m_sCallsign "#AR-Callsign_US_Company_A"
  }
  SCR_CallsignInfo "{6910F9F1D17367A7}" {
   m_sCallsign "#AR-Callsign_US_Company_B"
  }
  SCR_CallsignInfo "{6910F9F1D17367A8}" {
   m_sCallsign "#AR-Callsign_US_Company_C"
  }
  SCR_CallsignInfo "{6910F9F1D17367AA}" {
   m_sCallsign "#AR-Callsign_US_Company_D"
  }
  SCR_CallsignInfo "{6910F9F1D17309DD}" {
   m_sCallsign "#AR-Callsign_US_Company_E"
  }
  SCR_CallsignInfo "{6910F9F1D17309DB}" {
   m_sCallsign "#AR-Callsign_US_Company_F"
  }
  SCR_CallsignInfo "{6910F9F1D17309D9}" {
   m_sCallsign "#AR-Callsign_US_Company_G"
  }
  SCR_CallsignInfo "{6910F9F1D17309D8}" {
   m_sCallsign "#AR-Callsign_US_Company_H"
  }
 }
 m_aPlatoonNames {
  SCR_CallsignInfo "{6910F9F1D1730926}" {
   m_sCallsign "#AR-Callsign_US_Platoon_1"
  }
  SCR_CallsignInfo "{6910F9F1D1730925}" {
   m_sCallsign "#AR-Callsign_US_Platoon_2"
  }
  SCR_CallsignInfo "{6910F9F1D1730924}" {
   m_sCallsign "#AR-Callsign_US_Platoon_3"
  }
  SCR_CallsignInfo "{6910F9F1D1730923}" {
   m_sCallsign "#AR-Callsign_US_Platoon_4"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{6910F9F1D1730921}" {
   m_sCallsign "Spartan"
  }
  SCR_CallsignInfo "{6910F9F1D1730934}" {
   m_sCallsign "Orion"
  }
  SCR_CallsignInfo "{6910F9F1D1730932}" {
   m_sCallsign "Centaure"
  }
  SCR_CallsignInfo "{6910F9F1D1730931}" {
   m_sCallsign "Griffon"
  }
 }
 m_sCallsignGroupFormat "%3"
 m_sCallsignCharacterFormat "%4"
 m_sCallsignCharacterWithRoleFormat "%1 %2 %3: %4"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{6910F9F1D173093F}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{6910F9F1D173093E}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{6910F9F1D173093D}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}