SCR_ArsenalItemTypeUIConfig {
 m_ArsenalItemUITypes {
  SCR_ArsenalItemTypeUI "{691447E624AB999F}" {
   m_eItemType CGQC_TRAINING_ITEM
   m_Info SCR_UIInfo "{691447E6F8317282}" {
    Name "CGQC Training"
    Description "Objet servant au training CGQC"
    Icon "{A785C2D354BC7382}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Handwear.edds"
   }
  }
  SCR_ArsenalItemTypeUI "{6A0A20555E0F82CB}" {
   m_eItemType GRIT_ARMORY
   m_Info SCR_UIInfo "{6A0A20555E0F836D}" {
    Name "GRIT Amurerie"
    Description "Objet servant au GRIT"
    Icon "{A785C2D354BC7382}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Handwear.edds"
   }
  }
  SCR_ArsenalItemTypeUI "{6A0A2947C6E42D88}" {
   m_eItemType GRIT_ITEM
   m_Info SCR_UIInfo "{6A0A2947C6E42E09}" {
    Name "GRIT Item"
    Description "Objet servant au GRIT"
    Icon "{A785C2D354BC7382}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Handwear.edds"
   }
  }
 }
}