SCR_ArsenalItemTypeUIConfig {
 m_ArsenalItemUITypes {
  SCR_ArsenalItemTypeUI "{691447E624AB999F}" {
   m_eItemType CGQC_TRAINING_ITEM
   m_Info SCR_UIInfo "{691447E6F8317282}" {
    Name "CGQC Training"
    Description "Objet servant au training CGQC"
    Icon "{A785C2D354BC7382}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Handwear.edds"
   }
  }
 }
}