SCR_PlaceableEntitiesRegistry {
 m_sAddon "cgqc_core"
 m_sSourceDirectory "{DCF44154CA43E359}PrefabsEditable/System"
 m_Prefabs {
  "{9FDC165DE3771D3C}PrefabsEditable/Auto/MP/Spawning/E_SpawnPoint_CGQC.et"
 }
}