SCR_PlaceableEntitiesRegistry {
 m_sAddon "cgqc_core"
 m_sSourceDirectory "{3E46481B7CF16757}PrefabsEditable/Auto/Structures/Military/Flags/FlagPole_02"
 m_Prefabs {
  "{F1113070FA2635B9}PrefabsEditable/Auto/Structures/Military/Flags/FlagPole_02/E_CGQC_FlagPole_02_V1.et"
 }
}