ACE_SettingsConfig {
 m_aInitialModSettings {
  ACE_Medical_Core_Settings "{60FD72EFA3DB8236}" {
   m_fBloodRegenScale 0.5
   m_fSecondChanceOnHead 0.6
   m_bSecondChanceForFallDamageEnabled 1
   m_bSecondChanceForAIEnabled 1
  }
  ACE_Medical_Hitzones_Settings "{65A7596E8DE0F2A4}" {
   m_fSecondChanceOnHeart 0.2
  }
 }
}