SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{64734B162DA91179}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64744886951A1297}" {
     m_bEnabled 0
    }
   }
  }
 }
}