SCR_GroupRolePresetConfig {
 m_sGroupName "Véhicules Blindés"
 m_eGroupRole MECHANIZED
 m_sGroupFlag "{C756AD465925829D}UI/Textures/GroupManagement/FlagIcons/GroupFlagsBlufor-200_atlas.edds"
 m_sGroupFlagName "armored"
 m_sGroupDescription "Blindés du groupe CGQC"
 m_iGroupSize 6
 m_iRadioFrequency 39000
 m_sGroupRoleName "Blindés"
 m_aLoadoutResources {
  "{E3059771E7B40A41}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TankDriver.et"
  "{E3059771E7B40A41}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TankDriver.et"
  "{E3059771E7B40A41}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TankDriver.et"
  "{E3059771E7B40A41}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TankDriver.et"
  "{E3059771E7B40A41}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TankDriver.et"
  "{E3059771E7B40A41}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TankDriver.et"
 }
}