SCR_GroupRolePresetConfig {
 m_sGroupName "Escouade d'Infanterie"
 m_eGroupRole ASSAULT
 m_sGroupFlagName "infantry"
 m_sGroupDescription "Unité d'infanterie au coeur du groupe CGQC"
 m_iGroupSize 12
 m_iRadioFrequency 38000
 m_sGroupRoleName "Infanterie"
 m_aLoadoutResources {
  "{0D9FB99C2B45D948}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_SquadLeader.et"
  "{E8A2D7A04351EE26}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Medic.et"
  "{6AEBAAB77D2F7B3F}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TeamLeader.et"
  "{48BCFDE4B196C801}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_LMG.et"
  "{FDBB7219367F1ADB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Soldier.et"
  "{FDBB7219367F1ADB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Soldier.et"
  "{6AEBAAB77D2F7B3F}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_TeamLeader.et"
  "{48BCFDE4B196C801}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_LMG.et"
  "{FDBB7219367F1ADB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Soldier.et"
  "{FDBB7219367F1ADB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Soldier.et"
  "{FDBB7219367F1ADB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Soldier.et"
  "{FDBB7219367F1ADB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Soldier.et"
 }
}