SCR_GroupRolePresetConfig {
 m_sGroupName "Sniper Team"
 m_eGroupRole RECON
 m_sGroupFlag "{C756AD465925829D}UI/Textures/GroupManagement/FlagIcons/GroupFlagsBlufor-200_atlas.edds"
 m_sGroupFlagName "sniper"
 m_iGroupSize 2
 m_iRadioFrequency 39000
 m_sGroupRoleName "Sniper team"
 m_aLoadoutResources {
  "{043F0E81D9D810A9}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Sniper.et"
  "{105308FA3E54387F}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Spotter.et"
 }
}