SCR_GroupRolePresetConfig {
 m_sGroupName "Hélicoptère de Transport"
 m_eGroupRole HELI_TRANSPORT
 m_sGroupFlag "{C756AD465925829D}UI/Textures/GroupManagement/FlagIcons/GroupFlagsBlufor-200_atlas.edds"
 m_sGroupFlagName "helicopter"
 m_sGroupDescription "Transport Héliporté du groupe CGQC"
 m_iGroupSize 6
 m_iRadioFrequency 39000
 m_sGroupRoleName "Hélicoptère Transport"
 m_aLoadoutResources {
  "{75B9A7B67813A2F3}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_HeliPilot.et"
  "{75B9A7B67813A2F3}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_HeliPilot.et"
  "{75B9A7B67813A2F3}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_HeliPilot.et"
  "{75B9A7B67813A2F3}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_HeliPilot.et"
  "{75B9A7B67813A2F3}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_HeliPilot.et"
  "{75B9A7B67813A2F3}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_HeliPilot.et"
 }
}