SCR_GroupRolePresetConfig {
 m_sGroupName "Hélicoptère de Combat"
 m_eGroupRole SF_ASSAULT
 m_sGroupFlag "{C756AD465925829D}UI/Textures/GroupManagement/FlagIcons/GroupFlagsBlufor-200_atlas.edds"
 m_sGroupFlagName "helicopter-attack"
 m_sGroupDescription "Hélicoptère de combat du groupe CGQC"
 m_iGroupSize 4
 m_iRadioFrequency 39000
 m_sGroupRoleName "Hélicoptère Transport"
 m_aLoadoutResources {
  "{75B9A7B67813A2F3}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_HeliPilot.et"
  "{75B9A7B67813A2F3}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_HeliPilot.et"
  "{75B9A7B67813A2F3}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_HeliPilot.et"
  "{75B9A7B67813A2F3}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_HeliPilot.et"
 }
}