SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6907101F18EB768F}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{6907101F1BBFA028}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{6908DB0D310A81A5}" {
   m_sEntityPrefab "{53A6AB58CC155C86}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Moderne_Student.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6908DB0D310A8ED9}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6908DB0D310A8EDC}" {
     m_UiInfo SCR_UIInfo "{6908DB0D310A8EDE}" {
      Name "Élève"
      Description "Soldat en formation"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{6908DB0DD4E8E2DF}" {
   m_sEntityPrefab "{2896A3035CB85D11}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Moderne_Instructor.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6908DB0DD4E8E2A4}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6908DB0DD4E8E2A9}" {
     m_UiInfo SCR_UIInfo "{6908DB0DD4E8E2AB}" {
      Name "Instructeur"
      Description "Formateur"
     }
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}