SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{68B9080860BB52A0}" {
   m_aEntityDataList {
    SCR_EntityCatalogSpawnerData "{68B9080860BB529C}" {
     m_UiInfo SCR_UIInfo "{68B9083A5F3E76AB}" {
      Name "Soldat Moderne"
     }
    }
   }
  }
  SCR_EntityCatalogEntry "{6907101F18EB768F}" {
   m_sEntityPrefab "{6FC69726C73FBDFB}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Rifleman_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogSpawnerData "{6907101F18EB7796}" {
     m_UiInfo SCR_UIInfo "{6907101F18EB779A}" {
      Name "Soldat Training Moderne"
     }
    }
   }
  }
  SCR_EntityCatalogEntry "{6907101F1BBFA028}" {
   m_sEntityPrefab "{4422D33726403B54}Prefabs/Characters/Factions/INDFOR/CGQC/Character_CGQC_Training_Instructeur_Moderne.et"
   m_aEntityDataList {
    SCR_EntityCatalogSpawnerData "{6907101F1BBFA1B6}" {
     m_UiInfo SCR_UIInfo "{6907101F1BBFA1B8}" {
      Name "Instructeur Moderne"
     }
    }
   }
  }
 }
}