SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{69144A0C2124CD18}" {
   m_sIdentifier "Training"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69144A0CD8224BAC}" {
     m_sEntityPrefab "{D56665074AFBE025}Prefabs/Weapons/Grenades/Grenade_M69_Practice.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{690B5607E8493836}" {
       m_eItemType CGQC_TRAINING_ITEM
       m_iSupplyCost 0
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{690B5607E8493832}" {
         m_vItemOffset -0.015 0.015 0
         m_vItemRotation 0 -36 15.8
        }
       }
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69144A0CE030368B}" {
     m_sEntityPrefab "{92B78B46ADE6D2EF}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_Sim.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{690B5607E849D958}" {
       m_eItemType CGQC_TRAINING_ITEM
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69144A0C920F9C2E}" {
     m_sEntityPrefab "{AC4E6A0DCB26276B}Prefabs/Weapons/Magazines/Box_556x45_M249_200rnd_Sim.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69144A0C920F9D85}" {
       m_eItemType CGQC_TRAINING_ITEM
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69144A0D49A992FC}" {
     m_sEntityPrefab "{7A18BE7763E03F17}Prefabs/Weapons/Magazines/Magazine_545x39_Sim.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69144A0D49A99267}" {
       m_eItemType CGQC_TRAINING_ITEM
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69144A0D4F4EA67B}" {
     m_sEntityPrefab "{F74E9D59C5C8BFCF}Prefabs/Weapons/Magazines/Box_762x54_PK_100rnd_Sim.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69144A0D4F4EA7B9}" {
       m_eItemType CGQC_TRAINING_ITEM
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69144A0CAC4A9870}" {
     m_sEntityPrefab "{5E80EC58B7E2B23B}Prefabs/Weapons/Rifles/AK74/Rifle_AK74_Sim.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{690B2C9BB5549641}" {
       m_eItemType CGQC_TRAINING_ITEM
       m_eItemMode WEAPON
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69144A0D5D3057E5}" {
     m_sEntityPrefab "{8FBD535C36BC5311}Prefabs/Weapons/MachineGuns/PKM/MG_PKM_Sim.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69144A0D5D3054D3}" {
       m_eItemType CGQC_TRAINING_ITEM
       m_eItemMode WEAPON
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}