SCR_GearPoolConfig {
 m_aGearPool {
  "{E4C98F783EAB35FF}Prefabs/Characters/Handwear/Gloves_MechanixMpact/GRS_Fingerless_Gloves.et"
  "{62BF9FFDF9E7754C}Prefabs/Characters/Handwear/Gloves_MechanixMpact/GRS_Gun_Gloves_Base.et"
  "{17DAAF4DC71B2AC3}Prefabs/Characters/Handwear/Gloves_MechanixMpact/GRS_Gun_Gloves_Black.et"
  "{77B7FB17D040FD41}Prefabs/Characters/Handwear/Gloves_MechanixMpact/GRS_Gun_Gloves_Gray.et"
  "{7E731BF5CCE904CB}Prefabs/Characters/Handwear/Gloves_MechanixMpact/GRS_Gun_Gloves_MC.et"
  "{4A6BC92E27227A7A}Prefabs/Characters/Handwear/Gloves_MechanixMpact/GRS_Gun_Gloves_Realtree.et"
  "{39428D5F8D2E26B3}Prefabs/Characters/Handwear/Gloves_MechanixMpact/GRS_Oakley_Gloves_Black.et"
  "{ABB779CFC2E11E89}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_mpack_Covert.et"
  "{974EA340B1751B24}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_mpack_WolfGrey.et"
  "{4E37FE174E8C266C}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_mpack_Coyote.et"
  "{B9FA26F5990CDEDD}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_mpack_MC.et"
  "{1E991CD19C6F7659}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_mpack_Brown.et"
  "{8D4A4DF9111F0682}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_mpack_Blk.et"
  "{4F71E7468E78DDD2}Prefabs/Characters/Handwear/Gloves_Leather_01/Gloves_Leather_01.et"
  "{517075EB66AABA76}Prefabs/Characters/Handwear/Gloves_Wool_01/Gloves_Pig_BLK.et"
  "{18D5ED7897777A96}Prefabs/Characters/Handwear/Gloves_Wool_01/Gloves_Pig_FDE.et"
  "{22EEE7CF3DA50A80}Prefabs/Characters/Handwear/Gloves_Wool_01/Gloves_Pig_LT.et"
  "{B8C14DF37D749EB5}Prefabs/Characters/Handwear/Gloves_Wool_01/Gloves_Pig_RG.et"
 }
}