SCR_GearPoolConfig {
 m_aGearPool {
  "{94070D3B7CBE9E78}Prefabs/Clothing/CDD_Comtac4.et"
  "{1DCF7522CC9F863D}Prefabs/Clothing/CDD_Comtac6.et"
  "{27372B335BF26533}Prefabs/Clothing/CDD_Comtac6G.et"
  "{F85339DBC07A1156}Prefabs/Clothing/CDD_Comtac7G.et"
  "{3B19D1D39CDE2B9A}Prefabs/Clothing/CDD_Comtac7T.et"
  "{4C91E1F03CF56BC9}Prefabs/Clothing/CDD_OC_AMP.et"
 }
}