SCR_GearPoolConfig {
 m_aGearPool {
  "{7429DFF39CEF10BD}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_ATACS.et"
  "{557683B254E7C60C}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_ATACS_backwards.et"
  "{E3BDE9165BEC54F2}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_BLK.et"
  "{FD10E748C737C0E2}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_BLK_backwards.et"
  "{7F367417D74EC5BD}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_GRY.et"
  "{C8D27A42832A2B0F}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_GRY_backwards.et"
  "{5C7F97C0F257180B}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_MC.et"
  "{31406B8AF6BB4DB4}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_MC_backwards.et"
  "{8F5F63E96E7E4FDC}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_OD.et"
  "{0C5C33A79F921FE9}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_OD_backwards.et"
  "{20C05AF8047F741C}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_TAN.et"
  "{0806C36951B3C052}Prefabs/Characters/HeadGear/Hat_BallCap/Hat_ballcap_TAN_backwards.et"
  "{9F263AD420624725}Prefabs/Characters/HeadGear/Hat_Beanie/Hat_beanie.et"
  "{F14913F524AA2C55}Prefabs/Characters/HeadGear/Hat_Beanie/Hat_beanie_Black.et"
  "{F7A1E4712B220BFC}Prefabs/Characters/HeadGear/Hat_Beanie/Hat_beanie_green.et"
  "{B8297DA9CC5BFDAA}Prefabs/Characters/HeadGear/Hat_USMC_Boonie/Hat_USMC_Boonie_WD.et"
  "{E12126CDE731EED5}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/Hat_Boonie_US_01.et"
  "{8D75122D5BF561FB}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/Hat_Boonie_US_olive.et"
  "{19231774D1D67091}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/Hat_Boonie_US_TigerStripe.et"
  "{D8D9EE7F3966589E}Prefabs/Characters/HeadGear/Hat_Knitted_01/Hat_Knitted_01_red.et"
  "{F545C1BE7C99954A}Prefabs/Characters/HeadGear/Hat_Patrol_US_01/Hat_Patrol_US_01.et"
  "{56915D05E3190762}Prefabs/Characters/HeadGear/Hat_Patrol_US_01/Hat_Patrol_US_01_TigerStripe.et"
  "{9911F55EC05D1A64}Prefabs/Characters/HeadGear/Hat_Patrol_US_01/Hat_Patrol_US_02.et"
  "{057F24AC2E4CFC2A}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_AOR1.et"
  "{5911D98425FAAD84}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_BaseM81.et"
  "{77EF622E4C7DBBFD}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_Black.et"
  "{D249B4655946A23A}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_Coyote.et"
  "{83CECD8F6C78EC7B}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_DCU.et"
  "{57D4F7D43E1A0F91}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_Gray.et"
  "{1F544607B5155E11}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_MARPATW.et"
  "{7EEE32F41631BC6F}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_MC.et"
  "{6C71E9D47685D8D3}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_New_M81.et"
  "{CEB4C2CB3B4858DF}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_OD.et"
  "{FC660E4D17DDB945}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_OGM81.et"
  "{A2E0F62B878CD7F1}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/GL_Hat_Boonie_MTP.et"
  ""
  ""
 }
}