SCR_GearPoolConfig {
 m_aGearPool {
  "{350BDCE98F12ACDA}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Champs_ButtonUPShirt.et"
  "{A8DB98EE9BD37A8F}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Champs_ButtonUPShirt_Beige.et"
  "{A87950ABC7487F4B}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Champs_ButtonUPShirt_Checked.et"
  "{90AD15CA7C0F907E}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Champs_ButtonUPShirt_RED.et"
  "{75BCB5DFEC2B1675}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Champs_hawaiian_Orange.et"
  "{4BC8D619821CFF8E}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Champs_hawaiian_redWhite.et"
  "{BB193C8A6103E90C}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Flannel_Blue.et"
  "{C8C0857BCF162F19}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Flannel_Brown.et"
  "{FF0B0CCE7B101320}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Flannel_Gray.et"
  "{C959A828F9CAC119}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Flannel_Green.et"
  "{AAFF483CF7FF4862}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Flannel_Redd.et"
  "{B7EFFC2B137E5EF6}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/G2.et"
  "{B579C5767EF1AC7C}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Hoodie_Coyote.et"
  "{5BBB5825F2BCB9E5}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Hoodie_Green.et"
  "{5D53AFA1FD349E4C}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Hoodie_Black.et"
  "{D11C109ACDB6FEF1}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Hoodie_Grey.et"
  "{EF4FD4FF066E8E26}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/SuitShirt_Brown.et"
  "{7243DC311B1F74F6}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/SuitShirt_Gray.et"
  "{120783780E218836}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/SuitShirt_Plaid.et"
  "{A7ABD1C89B471434}Prefabs/Characters/Uniforms/Tops/Vergy_Crye/BPShirt_Brown.et"
  "{A632FC9BAD9BFA34}Prefabs/Characters/Uniforms/Tops/Vergy_Crye/BPShirt_Green.et"
  "{9A796E4DBEF2A5E8}Prefabs/Characters/Uniforms/Tops/Vergy_Long_Sleeve/Vergy_Long_Sleeve_AOR2.et"
  "{2B21A2F636483EA1}Prefabs/Characters/Uniforms/Tops/Vergy_Crye/Vergy_Crye_AOR1.et"
  "{715A432040EABAAC}Prefabs/Characters/Uniforms/Tops/Vergy_Crye/Vergy_Crye_BaseM81.et"
  "{2BC5172C03888972}Prefabs/Characters/Uniforms/Tops/Vergy_Crye/Vergy_Crye_M81.et"
  "{EDB998C9B424A3C6}Prefabs/Characters/Uniforms/Tops/Vergy_Crye/Vergy_Crye_MTP.et"
  "{443A73701395CFFB}Prefabs/Characters/Uniforms/Tops/Vergy_Crye/Vergy_Crye_New_M81.et"
  "{EB7A946807E5D302}Prefabs/Characters/Uniforms/Tops/Vergy_Crye/Vergy_Crye_RG.et"
  "{07CC9AB728F34367}Prefabs/Characters/Uniforms/Tops/Frog_Top/Vergy_Frog_Top_AOR2.et"
  "{C44514CE5A713CF3}Prefabs/Characters/Uniforms/Tops/Frog_Top/Vergy_Frog_Top_MARPAT.et"
  "{D0C27D8DB0CC73D9}Prefabs/Characters/Uniforms/Shirt_CottonShirt_01/Shirt_CottonShirt_01_V1.et"
  "{86E0117B630414B5}Prefabs/Characters/Uniforms/Shirt_CottonShirt_01/Shirt_CottonShirt_01_V2.et"
  "{5E4878BA1A8D0AE9}Prefabs/Characters/Uniforms/Shirt_CottonShirt_01/Shirt_CottonShirt_01_V4.et"
  "{637C5D826FE183DE}Prefabs/Characters/Uniforms/Shirt_CottonShirt_01/Shirt_CottonShirt_01_V3.et"
  "{D78000A3AAAC12AC}Prefabs/Characters/Uniforms/Shirt_CottonShirt_01/Shirt_CottonShirt_01_V6.et"
  "{AD56359A52437AE2}Prefabs/Characters/Uniforms/Crye_Shirt/CDD_crye_shirt_rolled_MC.et"
 }
}