SCR_GearPoolConfig {
 m_aGearPool {
  "{AB50BBCB1AAA0F31}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/Champs_Jeans.et"
  "{D02AC3019939C544}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/Champs_Jeans_Beige.et"
  "{2F8103E090647226}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/Champs_Jeans_Black.et"
  "{0C2B93FE945DA3D5}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/Champs_Jeans_Blue.et"
  "{54A1FB9D4A26F56F}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/CCU_coyote.et"
  "{7BD5836DF13E300D}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/CCU_Tan.et"
  "{870D8E55FA85AC87}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/CCUE_Black.et"
  "{DAD0B62BC637466B}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/LevisJeansBlack.et"
  "{2EB9670F3B01CE5A}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/LevisJeansBlackDirty.et"
  "{DBB2C34B6DC8BD60}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/LevisJeansBlue.et"
  "{5DEB9D34C77B56E9}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/LevisJeansDarkBlue.et"
  "{69991F76513A7F5A}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/LevisJeansDarkBlueDirtyyy.et"
  "{91FBFA1D9BDDCA9B}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/TacPants.et"
  "{526D547E58DB8AF8}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/TacPantsBlack.et"
  "{5485A3FA5753AD51}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/TacPantsGreen.et"
  "{A6996A6BBFA362AD}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/TacPantsNavy.et"
  "{467DE70E16397B61}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/WiderLevisJeansRegular.et"
  "{592193C2E001D57A}Prefabs/Characters/Uniforms/CCUE_JEANS_TACPANTS/WiderLevisJeansDarkBlue.et"
  "{190C81C1FF285E62}Prefabs/Characters/Uniforms/Bottoms/Tact_Pants/GRS_Vergy_Tact_Pants.et"
  "{93270559F2A1C5C5}Prefabs/Characters/Uniforms/Bottoms/Tact_Pants/GRS_Vergy_Tact_Pants_MARPAT_AOR2.et"
  "{B81ACB05BB8D058D}Prefabs/Characters/Uniforms/Bottoms/Vergy_Pants/Vergy_Crye_Trousers_AOR1.et"
  "{E22EFCEDA6F8E894}Prefabs/Characters/Uniforms/Bottoms/Vergy_Pants/Vergy_Crye_Trousers_BaseM81.et"
  "{E6E95938C4D6CFB6}Prefabs/Characters/Uniforms/Bottoms/Vergy_Pants/Vergy_Crye_Trousers_BMCTwoTone.et"
  "{040B70C17C646341}Prefabs/Characters/Uniforms/Bottoms/Vergy_Pants/Vergy_Crye_Trousers_DCU.et"
  "{6C03CC3AE904081F}Prefabs/Characters/Uniforms/Bottoms/Vergy_Pants/Vergy_Crye_Trousers_Coyote.et"
  "{EAB1187DABDBF636}Prefabs/Characters/Uniforms/Bottoms/Vergy_Pants/Vergy_Crye_Trousers_Gray.et"
  "{0603F3FF2B9FA241}Prefabs/Characters/Uniforms/Bottoms/Vergy_Pants/Vergy_Crye_Trousers_M81.et"
  "{CF4FF1060599BAD8}Prefabs/Characters/Uniforms/Bottoms/Vergy_Pants/Vergy_Crye_Trousers_MARPATD.et"
  "{A46B636E36171B01}Prefabs/Characters/Uniforms/Bottoms/Vergy_Pants/Vergy_Crye_Trousers_MARPATW.et"
  "{04CB403AE892473A}Prefabs/Characters/Uniforms/Bottoms/Vergy_Pants/Vergy_Crye_Trousers_Realtree.et"
  "{92F7862AA023E569}Prefabs/Characters/Uniforms/Bottoms/Vergy_Pants/Vergy_Crye_Trousers_RG.et"
  "{86BB79B9A2233780}Prefabs/Characters/Uniforms/Pants_US_M65.et"
  "{C6BE0A871E7DE807}Prefabs/Characters/Uniforms/Pants_US_BDU_TigerStripe.et"
  "{604BB72BE8E023C2}Prefabs/Characters/Uniforms/Pants_US_BDU.et"
  "{27364244288DA83B}Prefabs/Characters/Uniforms/Pants_TAZ83/Pants_TAZ83_01.et"
  "{27494A16F172A97B}Prefabs/Characters/Uniforms/Pants_Tanker_USSR_01/Pants_Tanker_USSR_01.et"
 }
}