SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5C62F7D8F3ED7EFC}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{6894FB621F1AC011}" {
     m_sEntityPrefab "{275CCF136F6FAC72}Prefabs/Items/Equipment/Radios/CGQC_Radio_343_us.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6894FD0654A48C5C}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68AA59117D26C1B3}" {
     m_sEntityPrefab "{8536E65879FDF49A}Prefabs/Items/Equipment/Radios/CGQC_Radio_152_us.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68AA59117D26CE7D}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}