SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68E3539E55E1C4DC}" {
     m_sEntityPrefab "{B385064A383A384B}Prefabs/Items/Equipment/Nightvision/PVS14/NVG_PVS14Dual_WP.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5DA708DE12D0BECA}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 20
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68E3539E406FEB09}" {
     m_sEntityPrefab "{96ABEE9BF5DA858E}Prefabs/Items/Equipment/Nightvision/PVS14/NVG_PVS14Dual_WP_ref.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68E3539E406FE8FF}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 20
       m_eRequiredRank CORPORAL
      }
     }
    }
   }
  }
 }
}