SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD5F7414CA4A}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5C62F7DF3C4A41EC}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{6894FB62145E66C3}" {
     m_sEntityPrefab "{F8335C83706008ED}Prefabs/Items/Equipment/Radios/CGQC_Radio_343_ru.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6894FD064FBFE548}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68AA5911E7D5049E}" {
     m_sEntityPrefab "{5A5975C866F25005}Prefabs/Items/Equipment/Radios/CGQC_Radio_152_ru.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68AA5911E7D5044F}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}