SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD5F7414CA4A}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5C62F7DF3C4A41EC}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{6894FB62145E66C3}" {
     m_sEntityPrefab "{9FDB23F2240C197D}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_1_343.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6894FD064FBFE548}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68AA5911E7D5049E}" {
     m_sEntityPrefab "{E82129A6CC014809}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_3_152.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68AA5911E7D5044F}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68AC334884C67A61}" {
     m_sEntityPrefab "{94A3DCC6DD03EEF4}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_4_163.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68AC334884C67BDF}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
       m_eRequiredRank LIEUTENANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68AF5AF969A1633F}" {
     m_sEntityPrefab "{270974080CF24D74}Prefabs/Items/Equipment/Radios Base/CGQC_Radio_4_163z.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68AF5AF969A16093}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
       m_eRequiredRank LIEUTENANT
      }
     }
    }
   }
  }
 }
}