SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{65944B46301DADEA}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{659464171838F8FE}" {
     m_sEntityPrefab "{25569C2962C8F381}Prefabs/Items/Equipment/Accessories/IFAK/Trauma_IFAK_Tan.et"
    }
    SCR_EntityCatalogInventoryItem "{65946419938788F1}" {
     m_bEnabled 0
    }
   }
  }
 }
}