FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{570EDB8787206B1C}" {
   Headcamo {
    "{43AA5BDFE4338F57}Prefabs/Characters/Heads/Head_White_02/Head_White_02_camo_US_01.et"
    "{2FFE6F3F58F70079}Prefabs/Characters/Heads/Head_White_02/Head_White_02_camo_US_02.et"
   }
  }
  VisualIdentity "{570CE64C784286B5}" {
   Headcamo {
    "{51636CA07EC51127}Prefabs/Characters/Heads/Head_White_03/Head_White_03_camo_US_01.et"
    "{FDC271A8FC924801}Prefabs/Characters/Heads/Head_White_03/Head_White_03_camo_US_02.et"
   }
  }
  VisualIdentity "{570CFDC06CAAD480}" {
   Headcamo {
    "{473E20387338226D}Prefabs/Characters/Heads/Head_White_04/Head_White_04_camo_US_01.et"
    "{4697EB99D27CDC4F}Prefabs/Characters/Heads/Head_White_04/Head_White_04_camo_US_02.et"
   }
  }
  VisualIdentity "{570CFDC05A2BFCE8}" {
   Headcamo {
    "{36B119F39289239E}Prefabs/Characters/Heads/Head_White_05/Head_White_05_camo_US_01.et"
    "{94ABF50E76199437}Prefabs/Characters/Heads/Head_White_05/Head_White_05_camo_US_02.et"
   }
  }
  VisualIdentity "{570CFDC037CCBCD3}" {
   Headcamo {
    "{A42053AFB05A218B}Prefabs/Characters/Heads/Head_White_06/Head_White_06_camo_US_01.et"
    "{A01F375D335C7A2C}Prefabs/Characters/Heads/Head_White_06/Head_White_06_camo_US_02.et"
   }
  }
  VisualIdentity "{570CFDC1C8B17A43}" {
   Headcamo {
    "{889ACA9FABA0471F}Prefabs/Characters/Heads/Head_White_08/Head_White_08_camo_US_01.et"
    "{9444E2D4C76B6423}Prefabs/Characters/Heads/Head_White_08/Head_White_08_camo_US_02.et"
   }
  }
  VisualIdentity "{588508C196393A8F}" {
   Headcamo {
    "{F915F3544A1146EC}Prefabs/Characters/Heads/Head_White_09/Head_White_09_camo_US_01.et"
    "{4678FC43630E2C5B}Prefabs/Characters/Heads/Head_White_09/Head_White_09_camo_US_02.et"
   }
  }
  VisualIdentity "{588508C1951A8A0F}" {
   Headcamo {
    "{7E7987E31FB379BF}Prefabs/Characters/Heads/Head_White_10/Head_White_10_camo_US_01.et"
    "{3A4B78A288F46331}Prefabs/Characters/Heads/Head_White_10/Head_White_10_camo_US_02.et"
   }
  }
  VisualIdentity "{646EFE2F4E1432F4}" {
   Headcamo {
    "{DE13575C57A58F7B}Prefabs/Characters/Heads/Head_livonianHead_1_camo.et"
   }
  }
  VisualIdentity "{646EFE2EB891B034}" {
   Headcamo {
    "{D00D13146A5280A1}Prefabs/Characters/Heads/Head_livonianHead_2_camo.et"
   }
  }
  VisualIdentity "{646EFE2EB1CCAFBF}" {
   Headcamo {
    "{D5F8D0D381007A17}Prefabs/Characters/Heads/Head_livonianHead_3_camo.et"
   }
  }
  VisualIdentity "{646EFE2EADAB1FE7}" {
   Headcamo {
    "{CC319B8411BC9F15}Prefabs/Characters/Heads/Head_livonianHead_4_camo.et"
   }
  }
  VisualIdentity "{646EFE2EA7292FD3}" {
   Headcamo {
    "{C9C45843FAEE65A3}Prefabs/Characters/Heads/Head_livonianHead_5_camo.et"
   }
  }
  VisualIdentity "{646EFE2E9C3DD2BD}" {
   Headcamo {
    "{C7DA1C0BC7196A79}Prefabs/Characters/Heads/Head_livonianHead_6_camo.et"
   }
  }
  VisualIdentity "{646EFE2E968B329D}" {
   Headcamo {
    "{C22FDFCC2C4B90CF}Prefabs/Characters/Heads/Head_livonianHead_7_camo.et"
   }
  }
  VisualIdentity "{646EFE2E8F2FB67A}" {
   Headcamo {
    "{F4488AA4E660A07D}Prefabs/Characters/Heads/Head_livonianHead_8_camo.et"
   }
  }
  VisualIdentity "{646EFE2E85497DFB}" {
   Headcamo {
    "{F1BD49630D325ACB}Prefabs/Characters/Heads/Head_livonianHead_9_camo.et"
   }
  }
  VisualIdentity "{646EFE2EFF0E9904}" {
   Headcamo {
    "{79F4532B99E076CC}Prefabs/Characters/Heads/Head_livonianHead_10_camo.et"
   }
  }
  VisualIdentity "{646EFE2DBD965B1C}" {
   Headcamo {
    "{59036BD8F5B2F1FE}Prefabs/Characters/Heads/Head_smolko_camo.et"
   }
  }
 }
}