FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{646EFE2F4E1432F4}" {
   Headcamo {
    "{DE13575C57A58F7B}Prefabs/Characters/Heads/Head_livonianHead_1_camo.et"
   }
  }
  VisualIdentity "{646EFE2EB891B034}" {
   Headcamo {
    "{D00D13146A5280A1}Prefabs/Characters/Heads/Head_livonianHead_2_camo.et"
   }
  }
  VisualIdentity "{646EFE2EB1CCAFBF}" {
   Headcamo {
    "{D5F8D0D381007A17}Prefabs/Characters/Heads/Head_livonianHead_3_camo.et"
   }
  }
  VisualIdentity "{646EFE2EADAB1FE7}" {
   Headcamo {
    "{CC319B8411BC9F15}Prefabs/Characters/Heads/Head_livonianHead_4_camo.et"
   }
  }
  VisualIdentity "{646EFE2EA7292FD3}" {
   Headcamo {
    "{C9C45843FAEE65A3}Prefabs/Characters/Heads/Head_livonianHead_5_camo.et"
   }
  }
  VisualIdentity "{646EFE2E9C3DD2BD}" {
   Headcamo {
    "{C7DA1C0BC7196A79}Prefabs/Characters/Heads/Head_livonianHead_6_camo.et"
   }
  }
  VisualIdentity "{646EFE2E968B329D}" {
   Headcamo {
    "{C22FDFCC2C4B90CF}Prefabs/Characters/Heads/Head_livonianHead_7_camo.et"
   }
  }
  VisualIdentity "{646EFE2E8F2FB67A}" {
   Headcamo {
    "{F4488AA4E660A07D}Prefabs/Characters/Heads/Head_livonianHead_8_camo.et"
   }
  }
  VisualIdentity "{646EFE2E85497DFB}" {
   Headcamo {
    "{F1BD49630D325ACB}Prefabs/Characters/Heads/Head_livonianHead_9_camo.et"
   }
  }
  VisualIdentity "{646EFE2EFF0E9904}" {
   Headcamo {
    "{79F4532B99E076CC}Prefabs/Characters/Heads/Head_livonianHead_10_camo.et"
   }
  }
  VisualIdentity "{646EFE2DBD965B1C}" {
   Headcamo {
    "{59036BD8F5B2F1FE}Prefabs/Characters/Heads/Head_smolko_camo.et"
   }
  }
 }
}