JWK_ModIntegrationConfig {
 m_sModGUID "66EB0E96506E1FDF"
 m_sLabel "cgqcff"
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{68EEE4563FB6891D}" {
   m_sTitle "Mission packs"
   m_ShopItemAttributes JWK_ShopItemAttributes "{68EEE4562971DB06}" {
   }
  }
 }
 m_aFactionAddons {
  JWK_ModFactionAddons "{68EEE457BFAFABFB}" {
   m_aTargetFactionRoles {
    AMBIENT
   }
   m_aAddItems {
    "{F3F6FAF14CE4C5B1}Prefabs/Items/Equipment/Backpacks/Backpack_MissionBag_Black_civ.et"
    "{11A12C68B1B781A8}Prefabs/Items/Equipment/Backpacks/Backpack_MissionBag_Blue_civ.et"
    "{F2CB17B00B48ACF1}Prefabs/Items/Equipment/Backpacks/Backpack_MissionBag_CB_civ.et"
    "{86D73C65BCE37599}Prefabs/Items/Equipment/Backpacks/Backpack_MissionBag_Red_civ.et"
   }
   m_LoadoutAddons JWK_LoadoutConfig "{68EEE4561793083E}" {
    m_aSlots {
     JWK_LoadoutSlotConfig "{68EEE456161B95DE}" {
      m_iType BACKPACK
      m_aChoices {
       "{F3F6FAF14CE4C5B1}Prefabs/Items/Equipment/Backpacks/Backpack_MissionBag_Black_civ.et"
       "{11A12C68B1B781A8}Prefabs/Items/Equipment/Backpacks/Backpack_MissionBag_Blue_civ.et"
       "{F2CB17B00B48ACF1}Prefabs/Items/Equipment/Backpacks/Backpack_MissionBag_CB_civ.et"
       "{86D73C65BCE37599}Prefabs/Items/Equipment/Backpacks/Backpack_MissionBag_Red_civ.et"
      }
     }
    }
   }
  }
 }
}