SCR_MissionHeader {
 World "{D36904C1C8545BA2}Worlds/CGQC_Training.ent"
 m_sName "Installation Aigle Noir 1981"
 m_sAuthor "Kaffeina & silent1"
 m_sDescription "Site d'entraînement secret de l'unité CGQC"
 m_sIcon "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sLoadingScreen "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sPreviewImage "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sGameMode "Zeus"
 m_iPlayerCount 64
 m_eSaveTypes MANUAL
 m_bIsArmavisionAllowedInMP 1
}