SCR_MissionHeader {
 World "{34B43325FC5B45D1}TrainingWorlds/CGQC_CampLacorne.ent"
 m_sName "Camp Lacorne 1981"
 m_sAuthor "Mazinski & silent1"
 m_sDescription "Complexe d’entraînement situé sur une île isolée, conçu pour couvrir l’ensemble du spectre opérationnel. Le site comprend une zone motorisée dédiée, des champs de tir multiples (25 m, 300 m, roquettes, grenades, bounding, knockout bunker), un champ de tir intérieur, un réseau de tranchées, une section mortier, des positions de tir longue distance, ainsi que des infrastructures CQB/MOUT. Une piste d’aviation permet le déploiement et le soutien logistique des unités."
 m_sIcon "{B8F3D271E7B1272E}UI/Textures/MissionThumbnails/CAH_BriarsCoast_Thumbnail_UI.edds"
 m_sLoadingScreen "{22332A1418648704}UI/Textures/MissionLoadingScreens/placeholder_3_UI.edds"
 m_sPreviewImage "{22332A1418648704}UI/Textures/MissionLoadingScreens/placeholder_3_UI.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_eDefaultGameFlags SpawnVehicles
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_bMapMarkerEnableDeleteByAnyone 1
 m_bIsArmavisionAllowedInMP 1
}