SCR_MissionHeader {
 World "{D36904C1C8545BA2}CGQC_Training.ent"
 m_sName "CGQC Training - Installation Aigle Noir"
 m_sAuthor "silent1 & Kaffeina"
 m_sDescription "Site d'entraînement secret de l'unité CGQC"
 m_sIcon "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sLoadingScreen "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sPreviewImage "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sGameMode "Zeus"
 m_iPlayerCount 64
 m_eSaveTypes MANUAL
 m_bIsArmavisionAllowedInMP 1
}