SCR_MissionHeader {
 World "{D36904C1C8545BA2}TrainingWorlds/CGQC_Training.ent"
 m_sName "Installation Aigle Noir 1981"
 m_sAuthor "Kaffeina & silent1"
 m_sDescription "Site d’entraînement clandestin de l’unité de préparation opérationnelle du CGQC. Complexe souterrain intégrant une zone CQB complète et un centre de tir à 14 couloirs. Chaque poste est équipé de cibles IPSC standards à distance variable, avec système automatisé de détection et d’analyse des impacts en temps réel."
 m_sIcon "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sLoadingScreen "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sPreviewImage "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sGameMode "Zeus"
 m_iPlayerCount 64
 m_eSaveTypes MANUAL
 m_bIsArmavisionAllowedInMP 1
}