SCR_MissionHeader {
 World "{198B735819C71244}worlds/Island_Rebuild_GM.ent"
 m_sName "Camp Lacorne"
 m_sAuthor "Mazinski & silent1"
 m_sDescription "Camp d'entraînement extérieur du groupe CGQC"
 m_sIcon "{B8F3D271E7B1272E}UI/Textures/MissionThumbnails/CAH_BriarsCoast_Thumbnail_UI.edds"
 m_sLoadingScreen "{22332A1418648704}UI/Textures/MissionLoadingScreens/placeholder_3_UI.edds"
 m_sPreviewImage "{22332A1418648704}UI/Textures/MissionLoadingScreens/placeholder_3_UI.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_bMapMarkerEnableDeleteByAnyone 1
 m_bIsArmavisionAllowedInMP 1
}