SCR_MissionHeader {
 World "{F10D31CEB40C8445}Worlds/Training/FortTharen.ent"
 m_sName "Fort Tharen"
 m_sAuthor "Mazinski & silent1"
 m_sDescription "Base d'entraînement extérieure du CGQC"
 m_iPlayerCount 64
 m_bIsArmavisionAllowedInMP 1
}