SCR_MissionHeader {
 World "{85CBD7C7B8F8C2D9}Worlds/CGQC_CampLacorne_Moderne.ent"
 m_sName "Camp Lacorne 2026"
 m_sIcon "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sLoadingScreen "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sPreviewImage "{7501E7ADB50ECC1C}UI/Textures/Missions/mission_preview.edds"
 m_sGameMode "Zeus"
}