SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 FactionColor 0 0.0467 0.3763 1
 UIInfo SCR_FactionUIInfo "{62394AA4B52816D2}" {
  Name "CGQC"
  Icon "{7108F71EA87FAD37}Configs/Factions/cgqc_faction_newLogo_black_128.edds"
  m_sNameUpper "CGQC"
 }
 m_OutlineFactionColor 0 0.047 0.376 1
 m_NotificationFactionColor 0 0.063 0.533 1
 m_NotificationTextFactionColor 0 0.063 0.533 1
 m_sFactionFlag "{174D8B3191295219}Configs/Factions/cgqc_faction_flag_newLogo.edds"
 m_FactionFlagMaterial "{192878F0AF87EE97}Assets/Props/Fabric/Flags/Data/Flag_1_2_RHS_CGQC.emat"
 m_CallsignInfo SCR_FactionCallsignInfo "{5CC8BB97E017CDBC}" {
  m_aCompanyNames {
   SCR_CallsignInfo "{55CCB792CD021D5C}" {
    m_sCallsign "Company_A"
   }
  }
  m_aPlatoonNames {
   SCR_CallsignInfo "{55CCB792CE6E998D}" {
    m_sCallsign "Platoon_1"
   }
  }
  m_aSquadNames {
   SCR_CallsignInfo "{55CCB792D10AD8F4}" {
    m_sCallsign "Spartan"
   }
  }
  m_sCallsignGroupFormat "%3"
  m_sCallsignCharacterFormat "%4"
 }
}