SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{68C2246CC7F2AD03}" {
   m_Info SCR_UIInfo "{68C2246CC7F2AAED}" {
    Name "CGQC"
    Icon "{7B7A5F0D2E0E6D8D}UI/Textures/Factions/cgqc_faction_newLogo_black_128.edds"
   }
   m_LabelType FACTION_CGQC
   m_LabelGroupType FACTION
  }
 }
}