FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{66DB3A62C42819ED}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{1B1F4BCCC3A54549}Prefabs/Characters/Heads/Head_Cloutier.et"
   Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
 }
}