modded enum SCR_ECharacterRank
{
    CGQC_CADET,
	CGQC_SOLDAT,
	CGQC_CAPORAL,
	CGQC_CAPORAL_CHEF,
	CGQC_SERGENT,
	CGQC_ADJUDENT,
	CGQC_ADJUDENT_MAITRE,
    CGQC_ADJUDENT_CHEF,
    CGQC_SOUS_LIEUTENANT,
	CGQC_LIEUTENANT,
	CGQC_CAPITAINE,
	CGQC_MAJOR,
	CGQC_LIEUTENANT_COLONEL,
	CGQC_COLONEL,
	CGQC_VETERAN,
}