SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68B15AA9C98B6AE0}" {
   m_sIdentifier "Medical"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68B15AA89ED9AF92}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{68B15AA8FA983818}" {
     m_sEntityPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B15AA8FA9839FF}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B15AA86FA3AA89}" {
     m_sEntityPrefab "{58CF3AB87C441295}Prefabs/Items/Medicine/AmmoniumCarbonatePackage/ACE_Medical_AmmoniumCarbonatePackage.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B15AA86FA3AA33}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B15AA8F97757B1}" {
     m_sEntityPrefab "{5B2FD067D70C1E8F}Prefabs/Items/Medicine/EpinephrineInjection/ACE_Medical_EpinephrineInjection.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B15AA8F9775766}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B15AA8F8314D07}" {
     m_sEntityPrefab "{D0434D5215B54181}Prefabs/Items/Medicine/MetoprololInjection/ACE_Medical_MetoprololInjection.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B15AA8F8314ACF}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B15AA8FDA3193A}" {
     m_sEntityPrefab "{02DD34077F51F65E}Prefabs/Items/Medicine/NaloxoneInjection/ACE_Medical_NaloxoneInjection.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B15AA8FDA3668E}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B15AA8FD1FF12C}" {
     m_sEntityPrefab "{9BBA766CD869002C}Prefabs/Items/Medicine/PhenylephrineInjection/ACE_Medical_PhenylephrineInjection.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B15AA8FD1FFE98}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B353A84E4FD7B5}" {
     m_sEntityPrefab "{661744F5F88B401C}Prefabs/Items/Medicine/NCDKit/ACE_Medical_NCDKit.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B353A84E4FD4F4}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B353A8416ED643}" {
     m_sEntityPrefab "{498EBFCE4936F47B}Prefabs/Items/Medicine/KingLT/ACE_Medical_KingLT.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B353A8416ED633}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B353A8437116C5}" {
     m_sEntityPrefab "{79379D4E43B29B88}Prefabs/Items/Medicine/ChestSeal/ACE_Medical_ChestSeal.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B353A84371168B}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B15AA8A3EA8D33}" {
     m_sEntityPrefab "{CE262EF537F2E47A}Prefabs/Items/Equipment/Accessories/IFAK/IFAK.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B15AA8A3EA8AB0}" {
       m_eItemType HEAL
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68B15AA8A2929E45}" {
     m_sEntityPrefab "{25569C2962C8F381}Prefabs/Items/Equipment/Accessories/IFAK/Trauma_IFAK_Tan.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B15AA8A2929E32}" {
       m_eItemType HEAL
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}