SCR_Faction : "{FC76EA6983CAA3EE}Configs/Factions/CGQC.conf" {
 FactionKey "CGQC_UPO"
 UIInfo SCR_FactionUIInfo "{68B908121C63B283}" {
  Name "CGQC Unité de Préparation Opérationelle"
  Description "Unité de Préparation Opérationelle du CGQC"
  Icon "{571CB87D306C0A64}UI/Textures/Factions/cgqc_faction_newLogo_UPO_128.edds"
 }
 m_aFriendlyFactionsIds {
  "CGQC"
 }
}