SCR_MissionHeader {
 World "{47E371065EA511A4}Worlds/AniFF.ent"
 m_sName "Freedom Fighters - Anizay"
 m_sAuthor "Hyperr Hydra"
 m_sDescription "Freedom Fighters - Anizay without Takistani factions."
 m_sDetails "Vanilla variant of FF - Anizay."
 m_sGameMode "Freedom Fighters"
 m_iPlayerCount 10
}