SCR_GroupRolePresetConfig {
 m_sGroupName "1er Groupe d'Intervention"
 m_eGroupRole ASSAULT
 m_sGroupFlagName "infantry"
 m_sGroupDescription "Unité d'assault du GRIT"
 m_iGroupSize 32
 m_iRadioFrequency 38100
 m_sGroupRoleName "Infanterie"
 m_aLoadoutResources {
  "{CA4695C3926A40CF}Prefabs/Characters/Factions/INDFOR/GRIT/Character_GRIT_operator_rattler.et"
 }
}