SCR_GroupRolePresetConfig {
 m_sGroupName "Renseignement"
 m_eGroupRole SF_RECON
 m_sGroupFlagName "recon"
 m_sGroupDescription "Service d'Observation et Renseignement"
 m_iGroupSize 32
 m_iRadioFrequency 39200
 m_sGroupRoleName "Infanterie"
 m_aLoadoutResources {
  "{A5FDF23D30D0FEAE}Prefabs/Characters/Factions/INDFOR/GRIT/Character_GRIT_base.et"
 }
}