SCR_GroupRolePresetConfig {
 m_sGroupName "3nd Groupe d'Intervention"
 m_eGroupRole ASSAULT
 m_sGroupFlagName "infantry"
 m_sGroupDescription "Unité d'assault du GRIT"
 m_iGroupSize 32
 m_iRadioFrequency 38300
 m_sGroupRoleName "Infanterie"
 m_aLoadoutResources {
  "{A5FDF23D30D0FEAE}Prefabs/Characters/Factions/INDFOR/GRIT/Character_GRIT_base.et"
 }
}