SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5D4A8E6F2C974413}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69CE27301BB390F2}" {
     m_sEntityPrefab "{BA5F723AAF06A07C}Prefabs/Items/Equipment/Nightvision/Vlite/vlite_mcolor.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69CE27301BB3909F}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}